* 显化法则资料如下：未整理
**
** COBRA:
** 所有实体世界显化出来的东西都是源自高维灵性世界的想法，我们一开始想要显化的东西都是一个想法和抉择，这个抉择会形成一个显化漩涡，然后这个显化漩涡会经过我们的光体门户来到实体世界。
** 如果大家知道这个原理，大家就可以用自己的专注来显化自己想要的事情，大家把注意力放在一个地方就可以打开一个门户进而显化自己想要的人事物。
** 如果想要显化一栋房子，可以买一个小模型屋放在自己的口袋里面，大家每天就可以从口袋拿出模型屋出来看，每天看，这个专注力就会开启门户让你显化出你自己想要的房子，大家真的不用担心，这是很有效的技巧，这个模型屋的样子就会和你理想中的房子是一样的。
** 如果大家不小心买错房子模型整天看的话那可能就会显化出不同的房子了，这显化技巧是非常具体精确的。所以买来的模型要尽量具体符合自己想要的。
** 我们可以做一个压缩突破模型放在每周实体聚会上面，大家聚会时就盯着模型看，大家都盯着模型看5~10分钟。
** 如果大家想要显化一个东西，最好的办法就是做一个缩小版的模型。如果大家想要太空旅行的话那么最好在家里买一个宇宙飞船玤的模型，这是一个非常具体的显化技巧。
** 现在我们已经做出了压缩突破的模型图片，大家可以使用这些图片去制作出压缩突破的实体模型，也可以做其它的显化用途上，这张压缩突破模型图片已经经过COBRA的确认，大家可以广为宣传使用。
** 
** 显化法则
** 柯博拉谈到显化过程以及罗斯柴尔德是如何以此获得权力并基本上控制了行星的。
** 我们必须对自己保持绝对诚实并在我们的生活中拥有足够的觉知去看我们是如何以及因何作出我们正在做出的那些选择的。否则的话我们的抉择会失真，我们的生活会偏离我们真正的目标。
** 一个相关例子是假设一个人想要获得来自其父亲的认可，因此选择了医学，接着成为医生这条道路。终于在晚些时候他意识到他想做一些完全不同的事情，一些他的心起初就真正想做的事情。
** 恐惧可以歪曲我们去看和选择我们真正想要显化的事物的力量。
** 就如上面那个例子反映的那样。这种恐惧只在缺乏对自己的诚实的情况下出现。
** 
** 显化法则有三个简单的步骤：
** （1）抉择
** （2）意志/呼请
** （3）行动。
** 每个思想和行动都会在无限的意识场域中创造出涟漪。我们比我们意识到的更加强大。
** 那些有着最强的与我是临在的连结的人知道这个真理。我们的我是临在正放射着我们信念的能量。
** 我们的思想以特定的频率过滤这股能量，接着这股能量滤过我们的情绪并最终显化为物质实相。
** 我们的信念可以改变世界。
** 我们正在这个星球上塑造着实相并且我们有强大的力量在协助我们——在天上以及地下。所以别害怕请求你真心想要的。圣哲曼说呼请然后你就会接收到。
** 来自于我是临在的抉择是更加强大有效的。我们必须如水晶般清晰并坚持我们想要的，不要摇摆不定。花点时间明确自己是值得的。
** 阴谋集团通过让我们认为知道自己想要什么并去追求它是自私的来误导我们。事件之后，显化会更加迅速地发生，在五维是即刻的。
** 呼请与意志涉及到使用我们的情感、想象和可视化来填充能量流，深入到我们想要的事物的细节。带着期待，但别沉迷于它，将其放下。然后无论如何，不放弃我们真心渴望的。
** 罗斯柴尔德知道这个并坚持了70年无论事情变得对他们来说有多困难。
** 行动就是根据你先前的抉择和呼请作出你被指引去做的行为，带着一种你渴望的已经显化的那股能量的体验去做，就像细胞语言一般。
** 
** 显化逆转法
** 我们可以显化，同样也可以反显化。只要简单地宣告“我不想要”我们生活中可能存在的许多我们不喜欢的事情，之所以存在就是因为我们没有作出对它们说不的决定。
** 我们有简单地直接离开某人或拒绝见他们的能力。我们可以在我们自己的环境-财产，家庭，关系等等中开始实践这一点，并将其扩展到整个行星层面。
** 144000人对阴谋集团说“不”将导致压缩突破。我们必须做出这个决定并保持专注。
** 
** 实相塑造
** 实相总是在持续地显化并在一个连贯的能量流中被创造出来。
** 如果我们认出在生活中起作用的部分并感激我们已经拥有的，我们就可以将这股显化之流扩展并创造我们想要的。注意这股能量的流动并拥有感激之心，我们显化的力量就会增强。
** 如果我们注意到事物的同步性，我们同样也能看出我们是如何与这股能量流连结在一起并经历实相的塑造的。
** 同样地，使用内在指引也会培养这个能力。愿意持续和坚持采取行动来朝向自己渴望的实相，以及脱离舒适区。
** 要有意愿通过物理的经验（不带评判地）周遭和内在增强的能量场域来扩展它.
** 同样地通过创造更高的目标和扩展我们的信念我们就可以扩展实相的球体。
** 接着柯博拉指导我们用一个非常物理的方式来协助我们自身的显化过程（之前他要求我们带杂志、大报纸、剪刀和胶水到课上）。我们分成小组，分享自己带的这些资源。
** 他要求我们将杂志中符合我们想要显化的事物的图片剪出来，接着当我们有了足够的图片，就把它们粘贴在每个大报纸上。
** 他给予我们足够的时间来做这个，这很有趣并协助我为整体进行考量的过程。
** 我发现和剪出的图片很接近我心中渴望的事物。当我将它们都粘连在一起时，这创造出一个有力的可视化。
** 之后柯博拉说我们可以观想我们的图片像一个在漩涡中旋转的朝向我们的能量场域。
** 我们可以对自己重复道“我的我是临在正在创造一个与行星交流的能量漩涡并吸引我想要的已创造和正在创造的情境到我的生活中。
** 显化 级别：专家



** 2017.3
** 
** 基本上每個人的我是臨在都會發送能量波到我們生活的第三維度世界，我是臨在連結最強的人就可以決定地球的實相。只要有一個人跟我是臨在有完美的連結，只要一個人就能解放地球。我是臨在祂會將祂的能量波發送到第七維度和七維以下所有的世界，這種能量波會經過很多層的過濾來到我們的現實世界。
** 簡單說一下。我是臨在會發送自己的能量波，接著我們的心智層和情緒層會把我是臨在的能量波轉換成一種頻率，接著往下降到情緒體，接著來自情緒體的能量再次沉降進來來到我們的現實生活。我們生活周遭就像是一層層能量過濾的結果。這就是我是臨在顯化實相的方法。現在說些細節。
** 每個人是無極限的，人是無極限的。宇宙中並沒有什麼是自然法則規範讓我們不能顯化的東西，你可以顯化任何的東西。科學家都說這個不可能、那個不可能，他們說自由能源不可能，他們說光速應該是宇宙最快的速度。這是因為科學家的知識和眼界被陰謀集團打壓，陰謀集團用負面科技打壓人類的眼界，他們想塑造一個到處都有限制和控制的世界，陰謀集團他們本身就了解顯化法則，這就是他們為何如此成功地控制這個世界，
** 我會簡單的說明向大家說明顯化法則。身體有肉體、情緒體、心智體，有辦法讓肉體、心智體、情緒體統合到一致頻率，我們就一定會成功。
** 
** 顯化三部曲
** 
** 第一步是抉擇、第二步是祈請、第三步是具體的行動
** 所有顯化事物的法則就是依循三個步驟，我會很細節的跟大家說，做些實際的練習，所以第一步是抉擇，人們很容易腦袋一團亂，有著各種願望和想法及專案想要完成。
** 有時會聽從父母的抉擇去做他們想要我們做的事情以及想要我們唸的學校，之後會發現都不是我們自己真正想要的。人心很容易因為各種期望和願望而被迷惑，所以顯化法則第一步要很清楚知道自己要的是什麼，如果完全不知道自己想要的是什麼，那麼顯化出來的只是一團迷惑。
** 抉擇第一步是要很清楚知道自己要什麼東西
** 每天花5分鐘去了解自己想要顯化什麼，每天花5分鐘就可以避免自己浪費人生。只要很清楚自己人生目標就能知道對於自己來說什麼才是最重要的。陰謀集團他們做的事情讓我們內心天人交戰，讓我們不知道要做什麼，所以陰謀集團一直想讓我們處於迷惘狀態。
** 有時要讓自己獨處，讓自己能夠思考我這一生想要什麼。很多心智編程會阻止人們了解自己人生的真正目標。我說一些讓大家了解一下。
** 有些心智編程會影響顯化能力。第一個是了解自己人生想要什麼是很自私的想法。如果為自己追求某種東西是很不靈性的行為，有很多洗腦教條都是這樣跟你講的。我會說:你的人生想法期望和啟發是來自我是臨在對你呼喊的縮影。
** 好比說現在有很強烈的指引告訴你想去南極洲，那可能是我是臨在告訴你想去南極洲。這些想法背後是有原因的。如果了解顯化法則的作法那就真的有辦法去到南極洲，抉擇就是關鍵。
** 抉擇並不是只要5分鐘就會變的東西，顯化法則要成功，前提是抉擇要一直不變，只要大家很清楚自己的抉擇，基本上是不會變的，可能會有些變化，但重要的大方向是不會改變的，因為你真的很清楚你要什麼，你的抉擇就是反應我是臨在對你的訴求。
** 很重要的是堅持再堅持絕對不要放棄，不管是遇到了什麼阻礙，不管別人怎麼說，永遠永遠不要放棄。
** 很多人會抱怨顯化法則不成功是因為他們一下子就放棄了，他們可能距離成功就只有臨門一腳，但卻在成功前就放棄了。顯化法則不光是要顯化出金錢而是要顯化出我是臨在的神聖意志。金錢只是一個工具，而我們要用這個工具(金錢)在這世界顯化出我是臨在的神聖意志。
** 參宿七的黑暗勢力在5,000年前引進了金錢奴役制度到地球上，但我們還是可以將金錢轉換成神聖工具完成理想的崇高目標，我們仍然可以用金錢顯化我是臨在的神聖意志。
** 聖哲曼在人間時他非常富有，他用金錢顯化人類的自由，他非常精通顯化法則。
** 你的抉擇就反應出來自我是臨在的意志，當你完全理解自己的時候。其實認識自我很簡單並不複雜，我們不要自欺欺人不要騙自己，對自己完全的誠實，如果真的很討厭一個人就讓自己承認自己討厭那個人，這樣你才有辦法轉換這個恨意。如果不承認自己的想法，這些情緒就會一直堆積在那邊。
** 有些人會做些錯誤的抉擇隱藏一些事物，或者操弄某些事物或做些很奇怪的事情。有些人所做的抉擇是為了得到父親/母親的認同，有些人並不想去唸醫學院，他們只想為了得到父親/母親的認同而去唸了醫學院，他們浪費了五年的時間學醫，他可能會變成很厲害的醫師，有著精湛的醫術，但那個時候他就像行屍走肉一樣每天工作8小時，當初只是為了完成父親/母親的期望。
** 他如果懂得顯化法則，他其實可以告訴自己真正的想法來得到父親的認同，那該怎麼做?其實他會發現只需要跟父親花幾個月時間溝通他就會認同我了，這樣他就可以改行去做藝術家。
** 這是一個來自我是臨在的正確抉擇和其它錯誤願望之間的差別，大家只要對自己誠實的話就會知道我再說什麼了。這個案例夠清楚真實了。
** 有時對自己不誠實的人會很恐懼，恐懼只會在你對自己不誠實的時候變得強大，只要很了解自己是誰就不會恐懼。陰謀集團沒有能力控制你，只要對自己誠實了解自己是誰，陰謀集團就不能威脅你也不能恐嚇你，因為你的我是臨在凌駕所有一切。所以只要你的意志夠清楚強大，將是宇宙中最強大的力量。因為你的意志顯化了我是臨在的神聖意志，祂會自行顯化。
** 羅斯柴爾德之所以可以過去那麼強大，是因為他們知道自己想要什麼，也有長遠的計劃。羅斯柴爾德家族的王朝始於250年前，當初的初衷很簡單，他們想要統治這個世界，他們之所以這麼成功只有一個原因，他們永遠不放棄一直堅持這個工作和目標，並且堅持了250年。
** 第一代羅斯柴爾德他也知道他沒辦活過250年看到這個計劃實現，所以接著他們第一代將他願望傳承給兒子再傳給孫子，他們花了70年就統治了美國，接著再花50~60年奪下俄羅斯，接著在花個幾年就拿下全世界了。之所以這麼成功都是因為他們願意花250年的時間準備和顯化。
** 聖哲曼也很清楚自己要什麼所以花了350年時間實現，我也很清楚自己要做什麼所以花了20年的時間在做這些事情，所以大家也很清楚自己做些什麼，頂多花幾年或者幾個月就可以了。
** 因為我們一定會比羅斯柴爾德成功，我們跟我是臨在的連結一定比羅斯柴爾德還要強，以全球觀點來看我們一定比羅斯柴爾德還要成功，這是鐵打的事實不會變的。
** 科學已經證實我們可以根據顯化法則顯化這個世界，唯一的事情是需要花些時間，因為全球有70多億人的意識不太清楚所以需要花些時間，這就是為什麼地球解放要花這麼長的時間。
** 但我們的意志比較強健，因為我們的意志非常的堅定，所以看到很多的事情和真相，看到自由能源、看到新金融系統、看到陰謀集團的一切、看到傳送門，拓展了大家的眼界。所以大家知道了大揭露也知道了事件，大家的願望就是希望看到這些事情的發生，所以同時也要做好相對應的準備。
** 我知道這已經花了很久的時間，對我來說也真的花太長時間了，但我還是不會放棄要持續往前推進。
** 羅斯柴爾德和耶穌會有他們的弱點，他們還是會一直推進。另一方面聖哲曼也在實現自己的抉擇，不管花200、300年他都不會放棄。有些人可能認為事件下禮拜發生，但他們準備好了嗎?大家可以想像一下聖哲曼經歷了第一次和第二次世界大戰，在一個局勢混亂的環境但仍然堅持下去。
** 大家想像正面秘密太空計劃(SSP)的人看到太空船爆炸；而且登月也取消了，美國在這40年來都沒有送人上太空。很多人在秘密太空計劃工作40年還沒看到完整的結果，有些人1975年就在秘密太空計劃工作，而且在一般人所能達到的最高職位每天日夜辛勞，但還沒看到成果。
** 但美國還是沒辦法把人送上太空軌道，現在2017年了，至今拖延了40年美國還是沒把人送上太空，大家可以想像黑暗勢力多想打壓人類上太空。也有正派人士在幕後努力，過一陣子就能突破了。他們花了40年打基礎，大家有沒有辦法打算再花40年為事件努力啊?(有!)
** 這時候意志就反應出我是臨在的神聖意志。
** 第一步:你不會放棄，你很清楚了解自己的抉擇就會反應出我是臨在的神聖意志。
** 第二步:就是祈請，祈請的意思就是用情緒吸引幫助顯化的各種人事物。
** 所以一旦有明確的意志就會和我是臨在建立清楚的能量管道，接著就可以用情緒加速催化這股能量流，可以用觀想或假裝看到了要顯化的目標了。也可以用情緒呼請光明勢力幫助自己想顯化的事物，可以呼請天使、可以呼請龍族、可以呼請抵抗運動，只要願意呼請他們，他們就會幫忙。
** 關於第一步的抉擇還要說些事情，關於抉擇的事情剛剛忘了說了，抉擇要盡可能的精確明確，抉擇要很具體。有些人可能只想要新車，抉擇要更具體一點，什麼樣的具體呢?如果我要一台車，我會說:我要一台全新的捷豹跑車。車上要有GPS導航、渦輪增壓還附加所有頂級配備。
** 有些人說:我想要第一次接觸、我想跟星際兄弟姊妹見面。那麼我應該要具體一點。好比說:我要昴宿星人在我家的後院降落。他們會跟我見面；邀約我進入飛船暢談10分鐘。抉擇越具體、目標越明確，就不會有些模糊不清的問題。
** 只要抓到各種精確細節就放到自己情緒和觀想畫面裡，不過有時會有些變化，有些細節好比那台捷豹可能是從金屬色或變白色，這只是小細節還好。如果真的完全精通顯化法則，可以顯化到每個目標的細節。精準的程度會讓人嚇一下。驚嘆:這根本就是我想要的東西。
** 有了明確的畫面就可以關注在那個畫面，但不要變成迷戀和癡迷了。一旦很清楚顯化法則，目標一定會實現。但人生一樣要往前邁進，不是說要說服自己，祈請是顯化法則的一部份，所以就一直的觀想成天在觀想，不是說這是顯化法則的一部份就踟躕不前。只要很清楚是顯化的一部份，顯化法則就一定會成功。把抉擇願望先放心裡然後過好每一天，
** 第三步:就是具體的行動。如果不拿出具體的行動，那麼什麼事情也不會發生。你可以下定一千個抉擇每天祈請，但不拿出具體行動什麼也不會發生。大家應該做的是訂定一個目標，朝那目標前進。
** 好幾千個網友每天看我部落格說事件還沒發生，但他們什麼也沒做。每天都在等金融重置，然後說他們在金融重置之後要蓋一千台超光速粒子艙。如果只是些空談沒有具體行動這樣什麼也不會發生。
** 雖然金融重置還沒發生，但這也是我們顯化的目標之一。如果只是癡心妄想什麼都不做那就什麼也不會發生。具體行動不是說要做很辛苦的事情或勉強自己，而是順應內在的指引；做自己該做的事情。就像是順著指引去南極洲。所以如果要去南極洲，我應該要訂機票然後打包行李或找人幫你打包行李，不一定要自己很費力的打包行李。
** 如果目標比較大的話，好比買新房子，你可以先上網找房子。就算現在沒有錢，就是要把能量場印刻在你想要的房子上面。只要你有辦法得到那個體驗，那個體驗會印刻在DNA裡面，能量場就會整合這個體驗，接著你就會陸續換房子，換到第二間、第三間，接著會把這個體驗整合到內在能量場，接著就能陸續換房子換到自己理想的房子。
** 好比說大家想要第一次接觸。大家可以先去51區了解當時的場景，或可能需要去羅斯威爾待上幾天。可能光看書還不夠，需要現場更實際的體驗。親身體驗就一個具體行動的案例。真的不需要害怕，一定要去做。
** 很多人來自世界各地，從世界各地來到台北參加這場會議。來到這裡就是一種具體的行動，每個人都不辭辛勞來到這裡，回過頭來看好像也沒多難，也不是多艱鉅的挑戰，每個人都來到了會議現場，恭喜大家。
** 顯化法則關鍵就是不斷的重複三個步驟:抉擇、祈請、行動。
** 接著好比說要一個新房子。我得決定買一個新房子，然後上網找房子把房子模樣刻印在腦海裡。然後拿出具體行動；找到新工作有更好的收入。接著就是祈請光明勢力來幫助自己，接著問朋友有沒有適合的房子，就這樣不斷地重複一直重複最後換到自己理想的房子。
** 顯化法則為什麼失敗?是因為太早放棄了所以失敗，顯化法則沒辦法馬上實現是因為我們住在稠密的實相，所以需要時間顯化。如果顯化一個午餐可能要花5~10分鐘，如果做一個可以用的自由能源機器可能要花5~10年，如果在三年研發期間都放棄了那就不會做出自由能源機器。如果要顯化新房子，常理來看可能要花10~20年。
** 就算懂得顯化法則想要一個房子也要3、5年的時間，如果第三年就放棄了那麼一切都白費了，如果你看過很多房子但沒去買，那就白做了。
** 開放提問:
** 與會者：我自己用顯化法則想要同時顯化六個東西會不會有影響，顯化力量會不會變弱?
** COBRA：你要同時顯化多少都可以，沒有影響。我個人目前在顯化四百個專案。
** 與會者：如果說我想要的東西有符合我的靈魂內在指引會不會比較快呢?
** COBRA：是的，會比較快一點。
** 與會者：我想請問高維世界存有為什麼能馬上顯化東西?
** COBRA：高維存有不會內在天人交戰。他們很清楚自己要什麼，他們心智體、肉體、情緒體是統合的，所以可以馬上顯化他們想要的。
** 與會者：我是一個兩個小孩的媽，我的顯化可以包含我兩個小孩嗎?
** COBRA：我講的顯化技巧都是為你個人使用的。你有你的自由意志，不管你小孩幾歲也擁有自由意志。有時父母也會忘記自己小孩有自由意志，養育小孩是一回事，但要強加自由意志在別人身上是另一回事。自己的目標可以包括讓自己的小孩可以有幸福快樂的生活，但不要顯化我小孩明天要穿這個衣服、明天去學什麼。如果小孩喜歡聽重金屬音樂那就讓他聽吧，就算他不喜歡聽巴哈古典音樂那也沒有關係的。
** 與會者：假設小我說我要買豐田汽車，但是高我卻希望給我賓士。請問小我的抉擇對高我來說是不是一種限制?
** COBRA：我來解釋一下。如果真的很明確了解自己要什麼，不管自己有多少錢一定要這台車，因為你的抉擇會吸引到可以幫助你顯化賓士的人事物，並不是每個人都要路上開著雙B。有些人就是喜歡開豐田的車。你要對自己誠實要很清楚自己要什麼，自己要豐田還是賓士，要知道自己到底想要什麼。
** 要稍微想一下可能要改變自己做事方法和自己看待價值觀的方式。
** 與會者：如果我真的想要顯化金錢，該怎麼做?
** COBRA：這個抉擇太模糊。我應該要想:我該顯化多少錢?錢怎麼來?好比說我想要銀行有10億。自己要想銀行帳戶或手上現金有多少錢，一旦有清楚的抉擇就可以開始顯化。
** 顯化金錢並不是屬於我是臨在的本意。我是臨在會幫助你顯化金錢，讓你想做的事情。如果今天錢沒有購買力，那它只是一張普通的紙而已。錢只是一個代表性的交易工具。重要的是你想要新車子、新房子或更好的人生。
** 如果目的是要錢和房子車子及更好的人生，那錢就會被吸引過來，所以比較重要還是你要錢來做什麼。好比你要一台新車，那麼買車的錢就會過來了。
** 與會者：假設兩群人精通顯化法則，但雙方顯化方向完全相反，那會發生什麼事情?
** COBRA：這是目前現在的狀態，也就是光明勢力和黑暗勢力非常精通顯化法則。大家想像地球上有兩家公司。一家是羅斯柴爾德公司，另一家為聖哲曼公司。
** 塑造實相
** 現在來說些進階知識。銀河聯盟會利用實相塑造技術來塑造想要的實相。我向大家解釋這些，大家可以帶回家使用。所有實相都是透過門戶來顯化的，我們現在所看到所有事物都是透過電漿門戶顯化到我們日常生活中。其實每個原子都是一個星門，都是一個撓場形狀的星門。
** 大家知道這就是女神漩渦
** 我們要利用女神漩渦的能量顯化我們的事物。現在來解釋一下，每一次的顯化都是靈性和物質互動的結果。昨天有講到我是臨在就是上面的靈性，我們的精神情緒和抉擇都透過這個往下到達這個轉捩化點門戶顯化在我們現實生活。剛剛提到顯化法則三大步驟最上面是抉擇，再來是祈請及具體行動，然後到了轉捩點的時候顯化就會發生了。
** 只要一直按照這三個步驟總有一天就會顯化成功。好比說為了一個房子已經顯化了五年，有一天突然開車看到一個房子就這樣買了。現在顯化一個目標到你生活的時候，其實有個方法可以大幅加速大家顯化過程，這個叫實相塑造法。
** 實相並不是一個死板板的固體而是內在意志的反射，所以可以利用實相塑造法來塑造我們的實相，用專注的意念塑造實相。
** 好比我關注這個如意寶珠，突然有一天幾百顆如意寶珠跑到我的生活裡面。如果想用實相塑造法就要有意識的專注在自己顯化的事物上，大家都知道自己生活的屬性，每個人生活屬性都不太一樣，每個人顯化的人生目標有不同抉擇，有些人可能在顯化的過程，也有人已經顯化了。
** 生活中一些實相有助於我們顯化也有些實相沒有幫助，好比我的身體健康狀況是OK的但其它方面可能不太好，好比用氣場照相機幫大家拍氣場照片，就能看到大家生活有什麼狀況。
** 如果要顯化一個實相永遠來自於一個當下，永遠關注生活中對自己有用的東西。好比我今天想顯化一台捷豹超跑，但我現在開的是豐田，然後覺得我必須開更好的車想甩掉舊車。但如果一直堅持開著舊車，那麼你可能就會越開越差的車，永遠開不到捷豹超跑。
** 大家可以這樣說:雖然我現在開的是豐田，不過我值得開更好的車。我能開到捷豹超跑，接著顯化就會朝這個方向演進。所以下一步就可能升級成奧迪或BMW，雖然還沒到達捷豹的目標但已經往那個目標邁進了。人生邁進一步就可以更上一層樓了。
** 假設現在有個人說:我口袋裝的如意寶珠好小顆。這時候你的意念應該要說這顆如意寶珠雖然小但是價值遠高於鑽石而且更珍貴。這樣子你就真的可以顯化出換到更好的。所以專注自己的意念，專注在更好的人事物上面，你專注的方向就像一個能量漩渦接著就會顯化。
** 我再說一次。如果我的想法認為:我這台豐田又舊又破，我想要甩掉這台車。可能就會有人想買走你的車。如果我的想法是我有台可以用的豐田，但是我還可以開到更好的車，結果就會是可以開到一台更好的新車。
** 實相塑造法的基本觀念是專注自己意念；用意識去拓展有用的部份。好比說現在有一間公寓，那麼可以感謝這間公寓，這樣一定會有更好的結果出現，接著就升級成一棟房子了。
** 實相塑造法像是一個正面思考。他不是單純發好願，而是有意識的讓自己的生活步步高升往上爬，就像已經很了解生活周遭處境，所以朝更好的目標前進，把好的變成更好的。
** 好比說不光是顯化的物體而是一個處境或者情境，不管是物體或情境，我是臨在的力量都可以進入這個情境來改善。
** 開放提問:
** 與會者：我們要如何用這個方法顯化事件?
** COBRA：用這個方法顯化事件時，要說感謝已經發生的事情，用這些基礎往事件邁進。好比說大揭露還沒發生，我們感謝現在已經有的努力，感謝已經發生的委婉揭露，讓我們朝大揭露邁進。
** 現在網路上出現了部份小揭露的文章，雖然不是陰謀集團全部被逮捕但已經有些被逮捕了，雖然新金融系統還沒上線但我們朝這個方向邁進了，上海黃金交易所是一個例子，中國有自己的交易平台。只要知道這些進展就可以有意識朝更好的方向發展。
** 與會者：有關於佈施福報和顯化法則的關係，我們常說要有佈施，才能夠有福報讓自己生活更好?
** COBRA：如果是把自己能量投注在地球解放事物上對自己也會有幫助的。如果正確的佈施就會把自己能量流分在有意義的地方上面。
** 與會者：感恩是不是實相塑造法的一部份?
** COBRA：感謝是有意識的了解現況知道現在的情形，但不是像新時代運動一樣感謝負面的人事物。我們要感謝宇宙中顯化給我們的恩典和人事物，但請不要感謝負面的人事物。
** 與會者：假設事件後有物質產生艙要顯化什麼物質都有，我們是不是還要感謝，用實相塑造法來顯化自己想要的東西?
** COBRA：物質產生艙和塑造法原理很像的，可以透過一步一步進階。
** 與會者：我是臨在是在哪個維度時空?
** COBRA：我是臨在無所不在，我是臨在是超越所有維度的存在並不侷限在特定維度，我是臨在和神聖本源是連接的。
** 與會者：剛剛提到統合能量場加速顯化，那探測術是不是也可以加速顯化?
** COBRA：沒有。現在說的是自然法則而不是一種操縱能量的技術。
** 與會者：我知道很多人都在想辦法顯化金融重置，那為什麼都還沒發生?
** COBRA：很多人在顯化重置但都是在做白日夢，都在癡心幻想完全沒有具體的行動。有些是基於錯誤抉擇錯誤決定才想讓重置發生，好比說有些人是想去買伊拉克第納爾、辛巴威幣想趁金融重置後套利賺大錢。
** 新金融系統不光是調整貨幣匯率，新金融系統是要全新打造全新的系統，很多人想要金融重置的都在做白日夢，就算有具體行動正在進行金融重置的人也需要花些時間，羅斯柴爾德花了250年打造現在的金融系統，我們想花10年左右做新金融系統，我們不需要花250年，我們過去花了10年，現在再花些時間就能看到成果了。
** 與會者：我們認為成功必須經過努力和受苦這個信念對顯化是否有牴觸或者不正確的?
** COBRA：受苦或犧牲才得到成功的概念是執政官創造的編程，他們就是要製造更多的苦難，所以他們就創造一個信仰系統說受苦受難是一種美德，顯化和受苦受折磨一點關係都沒有，那些事情沒有任何崇高的目的。
** 拜託不要再說地球是學校了，也不要花錢當卡奴。如果地球真是所學校，那麼有誰會想來這裡唸??
** 與會者：我可不可以透過設定心智讓我自己隨時和我是臨在合一而不透過冥想?
** COBRA：最好不要靠設定，用簡單的冥想和我是臨在連結。
** 與會者：關於中國金融系統。如果不在矩陣裡生活不去貸款當奴隸不給自己更多經濟壓力，顯化是否會更快一些，如果不去因為買房子而貸款去做更多有助於光的事情。
** COBRA：是的，非常好。
** 現在講顯化，等等詳細說明顯化逆轉。等等詳細和大家說明。
** 再來解釋一個重要的事情，如果用這個實相塑造法，我是臨在的能量就可以源源不絕的流進我們能量場，就可以一直使用顯化能量流。好比說這時可以同時顯化好幾個目標好幾個抉擇。有些抉擇非常重大，好比顯化事件發生這就是重大的。
** 宏遠的目標:好比我要解放整個宇宙。比較中層的目標:比如買新房子和有更好的生活，如果是小目標:我要一個CD，很快就能在網路上馬上找到這個CD。
** 用實相塑造法會有持續顯化能量流進入能量場
** 上面是我是臨在，下面是心智體、情緒體、肉體。下面是將能量顯化到現實生活。如果可以一直持續使用實相塑造法就可以拓展眼界看到正面的人事物和東西，只要跟我是臨在連結就可以獲得我是臨在的指引，收到的指引並不一定是最終顯化的目標，我是臨在給你的指引都是下一步的目標而不是告訴你完整的目標。等等會說個案例。
** 好比我要設定一個目標。就好比我今天要在夜間爬山攻頂。我現在的周圍是一片黑，手上只拿著手電筒照亮前面的路。我們僅需要知道路前面兩三步是不是安全的就可以了，只要用這個方法就可以在夜間完成攻頂。這就是內在指引的給我們提示的作法。
** 如果聽從內在指引就會告訴你下一步走到哪裡去。很多人都不想聽從指引，因為有時候內在指引會讓你走出舒適圈。好比說現在要去南極洲，內在指引會說去戶外用品店買件抗低溫的服裝。那時候你也許會出現覺得這衣服好貴之類的想法。
** 如果不聽從內在指引，你的內在指引就會越來越弱。如果聽從指引內在心聲就會越來越強。因為呼應內在指引，我是臨在就會給你更好的指引。只要順從內在的指引和實相塑造法，基本上可以顯化所有的事物。我透過這樣的技巧顯化了8、9成的抉擇了，我自己親身經歷了這些，這是有用的。
** 我知道那種長遠目標花比較多時間，但這套技巧是有用的，有時候會阻擋你擴展眼界的東西是恐懼。剛剛有人問關於金錢的問題，我要順便講關於眼界圈的事情。
** 每個人生活都是由眼界圈來決定的。有些人會有自我設限的想法，認為人生只要有車子有穩定工作就好了，這種眼界圈來自生活的經驗和價值觀。很多人的眼界圈不包括到外星球旅行，通常都是過很簡約的生活。很多人認為年收入10萬美元就很好，但是手上握有一百萬美元現金超過他們眼界了。
** 想顯化更好的東西就必須拓展眼界，而我們可以親身體驗一下你想體驗的東西。好比說真的想飛上太空和月球就去參加太空營隊，接著想登月就去參加太空營隊實際觀看太空船模型，這時能量就會印刻在我們身體裡面。
** 如果接收高我的崇高目標並且呼應那個指引，你的眼界就會提升，好比說一個人眼界一開始年收10萬美元就很厲害了，接著高我會給你一個經驗和體驗擴展你的眼界。高我給你一個機會讓你體驗開頂級超跑一個禮拜，接著可能會參加一個派對遇到讓你大開眼界的貴人。這時你的眼界圈和價值觀就被拓展了，因為你在體驗一些事情之後就會發現很多事情都是有可能的。
** 如果你想要登月，那麼你的眼界圈可能要拓展到跟伊隆·馬斯克見面，接著可以開始顯化你登月的費用:17,000,000萬美元。我說的是一個大概的理論，每個人都能做到你們想要做到的事情，說不定兩百個人明年就能一起登月了，這有什麼不可以。
** 拓展眼界相信這是可能的，你也做得到。即使我們花個3年時間去完成，這在自然法則也沒說這件事情行不通。我知道很多台灣人資產都超過1,700萬美元。這些大金主們何嘗不資助我們團隊呢?反正他們沒理由不資助我們。拓展眼界可以把任何事情變得可能。
** 花時間開展眼界讓自己相信這是可能的，事件發生的那一刻就是讓人類集體眼界擴大，讓大家認為說這是可能的。
** 現在開放提問:
** 與會者：我最近透過顯化法則顯化出我的目標，但這個目標引起家人不諒解，該怎麼辦?
** COBRA：我忘了解釋這個。我要說你的自由意志就是你的自由意志。不是每個人會同意你的自由意志，你可以決定什麼對你比較重要，很多人不認同我在做的事情，但我來自我是臨在崇高目標對我來說比較重要。你的家人不認同你顯化的東西但那就是你真正想要的。如果你家人真的愛你，那麼總有一天他會諒解你。如果他們不愛你，他們就根本不會在乎。你的人生自己好好過。
** 與會者：直覺算不算是一種內在指引?
** COBRA：是。不一定全部是。真正的直覺就是。
** 與會者：羅斯柴爾德他們跟我是臨在連結應該很弱怎麼還可以顯化這麼多東西?
** COBRA：答案會讓你嚇一跳，羅斯柴爾德跟他們我是臨在的連結也很強。他們是非常進化的一群人，他們跟內在有非常強的連結但他們的意識被植入物扭曲的非常嚴重。他們對世界的認知變得非常扭曲。羅斯柴爾德家族能使用內在指引，但會使用在做壞的事情，有些人精神力非常強，但卻會用自由意志做些壞事，這種問題在地球上特別嚴重，因為主要異常就聚集在地球。
** 羅斯柴爾德非常了解顯化法則，問題是他們誤用這些知識。我們自由意志比較強而且我們方向是正確的，這就是為什麼我們不需要再花250年顯化一個新的金融系統。
** 與會者：去醫院做志工算不算是一種內在指引?
** COBRA：當志工得到啟發那對你是好的，如果去那當志工獲得啟發就是自己的內在指引，那就是好的。
** 顯化過濾法
** 今天早上會議剩下最後一部份，現在來說實相過濾法。簡單來說如何不要在顯化生活中不想再度發生的人事物。剛剛教大家如何顯化想要的東西，那世界上也有你不想發生的事情，現在要來講怎麼做。
** 我們剛剛講到實相圈。這就是實相圈也可以說是眼界圈。在這個眼界圈裡面你決定什麼事情應該發生，哪些事情不該發生，透過抉擇來決定這些。
** 能夠連結我是臨在時讓這兩件事情同時發生。可以選擇不發生或發生。跟我是臨在完美連結之前這兩件事情也會發生但不是完美的，人生中有很多我們不想發生的人事物。過濾法原理很簡單，就是下一個抉擇。舉例說:我決定這件事情停止出現在我的生活。顯化逆轉法則讓這些事情停止出現在我的生活。
** 如果我的生活反覆出現同樣的困境，那並不是一個課程。你唯一需要學會的是下定決心對這些困境說不、立刻停止。我以前會遇到跟別人開會，別人一直遲到。我就一直等。有一天，我決定說:從現在開始，我只等15分鐘。如果對方沒出現我就要走了。這個方法，讓我15年來不但不用等別人，反倒是別人還要等我。
** 因為我不喜歡每次開會都要等人1、2小時，還要問對方會不會到。突然有一天我想我有辦法改變這個實相，之後我就下定決心，下一個抉擇說我只等15分鐘，再久就要走了。這個方法適用生活中各種狀況。如果是家暴受害者，那就對家暴說不，這些事情就不會發生在他們身上。
** 如果眾人的決心夠強大，決心對陰謀集團說”不”，他們就會被逮捕。根據顯化法則:如果人類集體對陰謀集團說”不”，他們就會被移除。
** 我們用顯化過濾法來過濾我們想要的實相，用同樣的顯化技巧來把不想要的實相排除在我們生活以外。陰謀集團之所以可以控制人類長久時間，就是因為人們對陰謀集團說:你們可以進入我的生活。所以人們相信必須守法、必須服從、過著受苦受難的日子。
** 有些人認為受苦受難有助於靈性成長，認為政府有權收稅，也有些人認為世道就是如此，逆來順受，將就就好。事實上我們有權說”不”。對不喜歡的事情說”不”這就是我們過濾實相的方法。
** 顯化逆轉法跟顯化法則一樣:拒絕實相發生也需要點時間，我們生活當中很多面向被控制。我們要下很多抉擇，對這些實相說不。我們必須對植入物說不，必須對化學凝結尾說不，對有毒的食物說不，對主流媒體說不，我們要拒絕的東西太多了，對每一個錯誤的人事物說”不”和”拒絕”都是一小步的勝利。
** 所有累積至今的問題都是過去人們覺得可以有網路審查、可以接受有毒食物、可以有政治監獄，讓各種不合理的事情把它認為是合理的。現在終於許多人受夠了，這就是一個覺醒的過程，覺醒不是虛無飄渺的說詞，也包括我們對於生活現況困境受夠了，對不想發生的事情說”不”，拒絕這些不想發生的事情，雖然可能說10次”不”裡會有一次的妥協。對於人類處境拒絕10次，可能會不小心妥協一次。
** 我們不光是顯化我們要的，也可以逆轉過去顯化的東西，可以先從小事情開始逆轉，生活周遭的環境開始過濾我們想要發生的實相，好比從生活居家住宅開始。
** 我們可以開始打掃自己的家裡，把不再需要的東西都清除。把家裡用不到的東西都丟掉，因為那些東西會阻礙能量的流動。大家也可以斷絕沒有用的人際關係，他們會耗盡你的能量。
** 開始培養對你有幫助的人際關係。你根本不需要有一千個不會關心你的臉書好友。說不定你也根本不需要有社交軟體，也不需要看電視，也可能不用每天滑手機上部落格然後發訊息。
** 執政官會讓人們一直沉迷於手機，一直分心。懂得過濾實相後，人生就可以往上進階，開始逆轉這些有毒的食物，接著可以用全球規模逆轉陰謀集團造成的負面結果。
** 一旦我們人類在集體意識上說”不”，對他們說”不”達到臨界質量，陰謀集團就不會存在，一旦有144,000人說”不”，陰謀集團就結束了。一旦有144,000人說”不”，地球上就會發生一個情境使得陰謀集團不適合在這生存。那個時候就是壓縮突破。
** 我們在2月26日的乙太層解放冥想達成了一半的”不”，我們在冥想後30分內維持抗拒陰謀集團的能量場看到了成果，事件後這種能量場將會永遠存在，我們將會用集體意識的力量對陰謀集團說”不”。
** 開放提問:
** 與會者：顯化事件的人和不相信事件的人在事件之後會有不同的實相，這是不是真的?
** COBRA：不會。事件是每個人都會經歷和面對的事情，不管你相不相信。
** 與會者：抵抗運動為什麼要叫抵抗運動?
** COBRA：抵抗運動這個團體的名稱在壓縮突破發生之前都還算是合適的，抵抗運動在壓縮突破完成之後就會融入銀河聯盟。目前抵抗運動的功能就是加速事件，因為他們在負責抵抗陰謀集團的活動我們才能活到現在，也包括我，要不然我今天也不會坐在這裡了。
** 與會者：如何使用轉化的門戶在自己的顯化逆轉法?
** COBRA：剛剛講到轉化點是個門戶，讓顯化的東西逆轉，一個東西就不再顯化了。人要觀注想顯化的實相而不是看想要的。一個堅定的抉擇可以讓這件事情不會發生了。下定決心決定你想要什麼，哪個事情不要發生。像是下定決心不要再等遲到的人，我不會關注對方遲到的實相，而是關注自己的部份，所以我只等15分鐘就離開了。
** 今天下午有很多事情要做，會非常的緊湊。
** 大家都到了嗎，今天來到第二階段，今天要專注於創造新的世界，今天早上講了如何使用顯化法則，現在就要用這樣的知識來顯化新的世界。
** 現在開放問答時間
** 與會者：地球從第三維度轉到第五維度的部份，這個人的頻率比較高的話有沒有可能在三維實相中存在於第五維度的狀態，像是揚升生活中?
** COBRA：當你有辦法達到第五維度意識後就不需要生活在三維世界裡，那時你的身體就不再只是身體而是個投影，但仍然會有個肉體，不過那是第五維度意識的投射。
** 與會者：我們華人的EVENT中文翻譯裡直接翻譯叫做事件，華人99%描述黑暗事物，這個對於讓我們分享事件的動作不太方便，社會大眾聽到會關閉他的心門，建議能夠選一個更好聽的中文名字，能方便分享，讓普羅大眾散佈這個好消息出去，是否支持這個改變?
** COBRA：我不懂中文我沒轍，不好意思。
** 與會者：光明勢力有沒有新的進展關於香港的，之前的都屬於全世界很久沒聽過香港，之前聽過香港說正面勢力黃金這邊之後就沒有了。
** COBRA：幾個禮拜之後會公開。
** 與會者：Cobra曾說過台灣是轉變的中心，我們承辦六次會議，為什麼當初會選擇來到台灣，台灣有什麼特別原因讓我們投生在這裡?
** COBRA：過去有一個很強大的靈魂團體一起旅行。這個靈魂團體和正面龍族有很強的連結。他們當時決定在這一世投生在台灣。
** 漩渦支持場(地圖)-特殊顯化技術
** 我們要講光體的能量場，(圖)這是我們的能量場，會用我是臨在有意識的創造出我們想要的實相。我是臨在會創造出一個漩渦場，這個漩渦能量場，可以吸引你希望顯化的人事物。
** 我們要來具體練習一次教大家如何使用這個漩渦支持場。基本上大家的我是臨在會形成一個漩渦支持場，可以說我是臨在形成一個漩渦能量場是電漿型態的能量場也是高維世界的能量場，這可以擴及整個地球。這個漩渦支持場可以吸引所有你要抉擇要顯化的人事物。
** 今天要來學習如何使用這個漩渦支持場。現在說些實際案例，我在很久以前想要賣些房地產，我不想用一般管道就用冥想開啟漩渦支持場，我就在冥想中設定意念，我觀想第一個買我房子的人今天第一天來到我家買下我的房產，然後隔天就接到電話說要買我的房產然後就買了，這就是冥想技巧的強大。
** 現在教大家如何使用這個漩渦支持場，現在我們更進一步使用漩渦支持場，用這個技巧幫大家顯化完美的人生，大家可以開始設計完美的人生去顯化完美的人生。
** 待會20~30個人分一組。我們要開始創造屬於我們的人生，我們要來使用心靈地圖練習顯化法則。
** 請大家在紙板上面描繪代表完美的人生的畫面。可以畫畫把你要的完美人生畫在上面，也可以把雜誌上代表完美人生的照片剪下來貼上去。把覺得漂亮美好的圖都剪下來，我們要用這個心靈地圖和漩渦加持場加速顯化你的完美人生。
** 現在已經做好一張代表我們完美人生的心靈地圖，如果還沒有做好的人休息時間可以繼續做。休息時間過後這邊要清空，稍後大家要一起來做個儀式。
** 休息時間前做一件事情。現在做個簡單的冥想，觀想身邊有個水平的彩虹漩渦(圖)；彩虹漩渦將你心靈地圖上面的人事物吸進你的生活；吸進你的身體。彩虹漩渦的旋轉方向沒關係，逆時針或者順時針都可以，將心靈地圖上面的人事物吸引到你的生活裡面。
** 
** 
** 彩虹漩渦示意圖(上下直立)
** 大家可以張開眼睛想像彩虹漩渦，將心靈地圖上面的人事物吸引進你的生活，這個就是你用來加速顯化過程的模板。20年前我做了人生第一張心靈地圖，大概在10年前我做了另一張地圖，第一張地圖有8、9成已經實現了，所以用了第二張地圖，第二張也有8成實現了。大家可以用心靈地圖當作是自己顯化的模板，大家可以使用彩虹漩渦加持場改變你的生活，不管什麼都可以。
** 大家也可以在實體聚會一起冥想，一起使用彩虹漩渦吸引大家想要的人事物，當大家實體聚會時可以一起用彩虹漩渦吸引大家共同想要的人事物，集體顯化力量比個人顯化力量還要大很多。
** 現在開放相關問答:
** 與會者：如意寶珠能加速顯化的原理是什麼?
** COBRA：如意寶珠用途並不完全是加速顯化，而是可以傳導事件的壓縮突破能量。如意寶珠之所以可以加速顯化，是因為它強化了配戴者與自身我是臨在的連結，因而可以更容易顯化你要的東西。
** 與會者：分享對於昴宿星創造者的概念?
** COBRA：他們心目中的創造者就是合一，就是神聖本源”絕對”。
** 聖哲曼黃金漩渦
** 現在要做一件事情。
** 在此共同呼請聖哲曼大師的臨在。我們要將聖哲曼的黃金乙太能量漩渦錨定在這，等等觀想黃金色乙太能量漩渦不斷向外擴展，實現我們最崇高的使命，實現我們在場每個人的崇高使命。
** 大家將貴金屬擺在桌上以順時針排列，走路的時候觀想彩虹漩渦，吸引更多的豐盛，邊走邊觀想吸引更多的豐盛，中間圍成一個圓圈，繞著聖壇圍著幾個圈。
** 現在觀想聖壇出現一個彩虹漩渦。現在觀想這個聖壇就是一個我們剛剛做的心靈地圖。觀想彩虹漩渦聖壇上的黃金和白銀吸進地球的能量場；為全人類帶來很多黃金白銀，帶來很多財富自由。
** 觀想彩虹漩渦讓全地球人類帶來豐盛，這是聖哲曼大師的偉大計劃也是我們正在做的計劃。
** 現在桌子是我們的能量錨定點，可以為我們帶來全部的豐盛。大家可以帶回去早上帶來的黃金白銀當作是自己的錢母隨身攜帶，它可以幫助加速我們的豐盛，這就是我們的錢母，一切如是如所祈願，阿門。
** 閉上眼觀想彩虹漩渦幫助我們完成崇高的使命。等一下從外圈開始拿回自己的金幣和銀幣，按照順序拿回自己的金幣和銀幣。
** 繼續回來排一個圓，現在大家手上拿著錢母，大家可以在未來使用錢母，可以讓我們財富倍增，如果帶銀幣未來可以帶來很多銀幣。我們做錢母儀式很成功。
** Jedi:我們在2014年7月Cobra教我們財富豐盛儀式，那時團隊只有兩個超光速粒子艙，現在已經有9個了，當時只有三個療癒中心，現在有8個了。還有很多人在這個儀式過程中得到非常好的顯化，生意變好或者財富變多了。
** 本來是去上班後來自己做生意就非常成功的，本來我在那時財務上是很緊的，現在已經變得更加輕鬆可以完成更多的工作。謝謝聖哲曼大師。
** 只要大家呼請聖哲曼大師，聖哲曼大師就會與你同在，現在幫聖哲曼大師的錨定，大家喜歡和金和銀一起工作，它會為你和周遭親朋好友帶來豐盛。
** 休息時間。
** 創立光之社區
** 我們要進一步的顯化新世界，我們不要等待事件，我們要親自顯化事件。過去講過幾次光的社區，去年七月講過光之社區。大家大概知道了一點概念。聖哲曼大師指示我，不要等待事件，我們要現在開始創建光之社區，現在我們要打造地球上第一個光之社區。
** 在幾年前有一些龍族已經選定好光之社區的場地，現在請Alex解釋現況。我稍後會補充。
** A：好久不見。地球上有些一般民間人士可以使用的龍門門戶。這些門戶分佈在地球上某些角落。龍門是通往地下阿加森世界的門戶，龍門不受政府或其它單位的掌控，現在我們發現了一座龍門，一個和我們合作的團體買下這個區域，買下的土地和龍門還滿接近的幾乎都在上方，跟我們龍族合作的團體買下很多龍門和龍門周遭的土地。
** 生活在這些土地周遭的村民流傳一項傳說:說這些土地上會有龍在盤旋，現在已經有這樣的土地可以開展地球上第一座光之社區。
** 光之社區形成的條件需要一塊土地，底下是亞特蘭提斯的舊赤道，有一塊土地在泰國。
** COBRA：有內在指引想住在光之社區的話可以用mail聯絡我，台灣地區的話聯絡請找Jedi，大家就可以收到進一步的指示。
** 光之社區的基本原理是要用神聖幾何來建造建築物。一位建商會用神聖幾何蓋房子，他的房子造價比外面便宜很多，結構都是半圓形類似巨蛋一樣，他們尺度都是按照神聖幾何打造的。
** 基本概念就是說感受到內在指引就買下這間半巨蛋型的房子，然後開始住在裡面，這是興建光之社區的第一階段。雖然執政官還沒被移除，陰謀集團也還沒垮台，但我們不能再等待了。現在就開始創造光之社區，有興趣的話可以連絡我或Jedi，我會給參與者進一步的指示。加入計劃的人我會加以審查。當然，現場的各位已經準備好可以加入這個光之社區了，對這個計劃有興趣的人可以連絡我和Jedi。
** 這個社區並非蠻荒部落，社區中有網路、有水、有電，基本上就是一個基礎設施很完善的社區，會請建商預鑄好建築的結構，然後到現場組裝。
** 這個社區裡面有個重要的關鍵，那就是社區裡面人與人之間的人際關係。執政官傾向創造人與人之間的衝突，雖然我們越來越接近壓縮突破，但住在這個社區的人一定要學會守望相助互相合作，雖然是自己買一棟房子住在這裡，但還是得互相合作彼此融洽生活。
** 住在光之社區目的就是要錨定聖光，顯化聖光。這應該會是第一次公開接觸之前會有飛船降落的地方，我們要創造光之社區跟(圖片)景象很接近。
** 與會者：請問光之社區的居民還需要用錢嗎?
** COBRA：目前光之社區還是要用到錢，還是得用錢買食物和所需要的服務。
** 與會者：請問光之社區跟烏本圖、維納斯計劃有關嗎?
** COBRA：和維納斯計劃無關。光之社區屬於新亞特蘭計劃的一部份。
** 目前外國人要加入這個社區的方法是我們跟這家公司合股，透過公司名義獲得土地。
** 我們要興建的光之社區附近就有森林、蔬菜、水源，所以不會匱乏，也可以用這塊森林打造有機農場。
** 這個光之社區蓋好之後電力來源會是太陽能和其它替代能源，水源主要是地下水。
** 至於價位和搬遷費用請聯絡Cobra或找Jedi詢問。
** 與會者：請問我搬進去之後就要永遠住在光之社區嗎?
** COBRA：搬過去只是在那蓋房子不用永遠住在那邊，可以邀請朋友一起去住。
** 交通還算方便，當地會有接駁巴士。距離市中心30分鐘，基本設施都有。
** COBRA：這是獨立專案，和其他聽到團體無關。
** 與會者：房子是一般住家住的房子還是家庭住宅?
** COBRA：這些房子大小可以依照需求而定，看有多少土地再來決定蓋多大的房子。
** 與會者：Cobra會參加這項計劃嗎?
** COBRA：我不會自己親自跑去當村長，我只是給大家一個機會創造新的世界。
** 光之社區會圍繞社區活動中心開始擴建，計劃還在發展階段，可以跟當地建築師、工程師合作打造光之社區，一起集思構想打造理想的社區型態。光之社區就是事件後的模範社區，讓大家知道如何生活，我們現在著手先做才不會都只是空談。
** 我們會按照這個模範社區當作範本，在各地複製打造各地當地的光之社區，清邁將會有一個光之社區。
** 與會者：這個社區這裡居住的人他的國籍怎麼辦，屬於哪個國家，出入怎麼辦?
** COBRA：所有國籍的人都歡迎加入只要你有心都歡迎加入。並不需要放棄原本的國籍。
** 與會者：要在那邊生活是不是得找到工作才能搬到那邊，還是當地可以提供工作機會讓我們在那能夠生活。
** COBRA：初期可能沒有工作機會，未來安定後大家可以使用網路創業。我不當老闆的。大家可以做些合法又正當的事情來獲得收入。
** 算是種子模範社區，這個社區還有很多我們沒看到的願景，我們走一步看一步，如果有新的想法也可以來做看看。
** 大家要把光之社區當作房地產投資的話也可以，只要在合理的情況下，住兩個月另外10個月租給別人。這是不會公開給社會大眾知道的社區必須嚴格審核才能住進來的。
** 雖然光之社區是獨立互相合作，這裡沒有村長和牧師，沒有誰比較高尚也沒有種族歧視，這不是Cobra邪教。我自己只是提供這個機會跟資訊而已，這不是要搞Cobra個人崇拜。
** 與會者：你們會跟烏本圖合作嗎?
** COBRA：如果烏本圖願意配合當然是很好。不管是烏本圖或者維納斯或者新亞特蘭提斯計劃，只要對人類好的都可以合作。這是我們自己要主動出擊的一種創辦社區計劃，我們要自己走出第一步，我們也歡迎大家互相交流經驗。
** 我們繼續。現在大家都知道顯化法則原理了，大家住在這裡不用擔心金錢問題，大家都懂得顯化法則金錢就不會是個問題，既然大家都知道顯化法則，自然能顯化出旅費和適當的生活費來到這個社區。只要第一個社區建好之後，其它社區也會在世界各地以指數性的成長。這並不像是傳統的社區裡每個房子長得都一樣，我們要打造的社區代表全新的世界，雖然同樣叫社區但在本質上是不一樣的，在這個光之社區不會推行宗教信仰，大家只要互相共處就行了。
** 將來大家可以顯化一個白水晶切出來的浴缸，超光速粒子白水晶切出來的浴缸。只要有願景願意做就一定會做到，用這種浴缸洗澡等於每天用超光速粒子水洗澡，當然我們會研發新的科技，將來會在這社區安裝超輸出裝置，將來會普及到全世界。唯一邊界就只剩下天空了。
** 我們可以引進一些現有的科技，現在歡迎Alex介紹對人類非常有幫助的雷射科技。
** Alex：我簡單介紹這些科技的原理，我們都知道身體有個光體有時候會為氣場，在可見光以外的身體，這個光體跟我們身體所有系統細胞相連的。光體連結到情緒和心智，光體也連結到乙太和更高維度的能量身體，我們也知道身體有經絡，他也像電纜線一樣連結來自內外的能量，穴位經絡就是體內的電漿線性通道，氣場就是個電漿場。
** 身體也符合碎形原理。 耳朵可以看到身體全部症狀，眼睛也是，耳朵就像眼睛的縮影，丹田也是全身的縮影和全身有連結的，手腳穴位都能反應身體的狀況。
** 我們也可以用各種方法影響身體周遭的能量場也就是氣場，我們也可以用氣場照相儀來看氣場有沒有改善，
** 我們知道植物會有光合作用，吃這些植物時實際上是在吃植物裡面的光，蔬果裡面有彩虹的顏色，當我們吃蔬果時都在吃下不同頻率的光。
** 我們的虹膜也跟身體所有細胞有連結，所以看一個人的虹膜就能知道一個人身體器官的狀況了。我們用不同顏色的光，再用光所攜帶的資訊就可以影響那個人身體的系統和器官，已經有科學研究證實光可以修復受損的細胞，這叫做光修復效應。
** 光能醫學有各種可能性。今天就不提太多。曼陀羅光能儀使用的是諧振的光波也就是雷射波，是種在量子層面的光。這台機器裡面內建各種諧振頻率資料庫，一旦使用資料庫可以從身體產生身心靈各方面的影響。
** 這台機器裡面有些資料庫的頻率算是身體的基礎頻率。這些頻率會告訴身體應該用什麼樣的頻率進行振動，身體細胞有時振動頻率太高或太低不在理想的狀態，只要我們對身體使用正確頻率就能對身體的頻率進行校準，現在大家可以看到這台機器。
** 大家已經很熟悉這台機器了，我們也在研發更多的好料，這是第一次展示這項技術，這個穹頂狀的裝置。
** 這有點像純量波產生的裝置，這個裝置除了可以散發光子場。這個可以產生光子場還能產生純量波場，還能使用導光水晶的用法。
** 也可以把這些資訊輸入水裡面，透過喝水吸收正確的頻率，有些人知道順勢療法，可以把那藥物打到水裡面進行順勢療法。基本上有這台光能儀就像在自己家開個藥局。也可以用這台儀器設定水晶，我們可以在水晶上設定很會演講學習語言的程式，或者幫助你放鬆的程式，把他帶到身體上面就有相對應的效果。
** 這個是我們正在開發中的雷射墜飾，正式版會漂亮些，會放入已經設定好的水晶，接著雷射會幫忙散發水晶設定好的程式，這個水晶墜飾就像擴大器一樣透過雷射放大水晶裡面設定好的效果。
** 這些機器都有搭配一台曼陀羅掃描儀，掃描這個人身體需要哪些程式，也可以用平板選擇自己想要的程式。
** 與會者：這台機器可以修復DNA嗎?
** Alex：這台機器有特定程式可以清除DNA負面記憶和想法甚至可以修復DNA。
** 科學家其實知道可以用近紅外線照射粒線體來修復整個細胞。基本上這有可能恢復人類潛藏的12股DNA?
** 與會者：可以用這台機器治療癌症嗎?
** Alex：這台機器不能宣稱有任何療效，只能說用光線紓壓並且調節免疫系統；進而有助於改善癌症患者的生活
** COBRA：待會有興趣的人可以在後面跟Alex聯絡。
** 這是我們未來一部份的縮影，我們現在開始顯化光之社區，還有新科技和超光速粒子浴缸。
** 揚升光柱
** 現在來說揚升光柱。到底什麼是揚升光柱，昨天有講到我是臨在，現在要做個冥想呼請我是臨在，透過揚升光柱進入自己的身體，昨天冥想做的光柱其實就是揚升光柱，揚升光柱其中一個面向是來自我是臨在的光柱貫穿三維世界的肉體。
** 揚升光柱另一個面向是銀河聯盟母船發送光柱到我們肉體，現在銀河聯盟母船停泊位置是在地球內部屏障內，昨天講到過去三年銀河聯盟母船停泊在太陽圈之外，去年文章寫到昴宿星人在地球周圍搭載超光速粒子內部屏障，12,000公里，內部屏障是距離地球12,000公里高的地方，那算是章魚的頭部頂端。現在銀河聯盟母船駐紮在這個區域，銀河聯盟母船就駐紮在章魚的頭外面。
** 大家可以用意識與銀河聯盟母船連結，大家可以觀想這道光柱從銀河聯盟母船發出，想像銀河聯盟母船發出巨大的能量光柱到我們身體上面。大家呼請揚升光柱的臨在，揚升光柱就會降下來，這個揚升光柱會進入我們肉體，這個揚升光柱有助於你個人的揚升，從現在開始到未來。現在大家知道銀河聯盟母船的駐紮位置了，我們現在就可以用意識連結銀河聯盟母船。
** 銀河聯盟母船從所在位置發射揚升光柱到我們肉體，只要經常連結這些光柱，這些光柱就會越活躍。
** 就會越來越有可能和銀河聯盟母船有接觸和面對面的交流，銀河聯盟母船上的光之存有們非常想和我們交流接觸，這是我們和他們交流的方式。現在我不會在這做大規模的儀式，目前還有點太早。
** 如果未來幾年還沒發生事件，還有辦會議的話我們就會在這進行，現在只是初期而已，揚升光柱是聖光的脈衝粒子，可以調和並保護我們的能量場和肉體。揚升光柱是非常先進的揚升科技，並不是憑空想像的東西，他是直接從銀河聯盟母船發出的能量波貫穿我們身體。
** 而進階版的揚升光柱會把人傳送到銀河聯盟母船上面，我們目前處於初期階段，透過觀想揚升光柱可以讓我們更容易連結到銀河聯盟母船，未來階段揚升光柱甚至可以把你傳送到銀河聯盟母船上。
** 揚升光柱也可以清除生活周遭的主要異常和保護你。我們即將進入銀河大團圓的初步階段，我們很快就要重獲自由了，我們總算可以回家了。大家還想待在這裡的話歡迎留下來，想回家的人就請自便。(圖)
** 在這之前，大家必須覺醒回想自己的使命並且100%投入。我們在這分享聖光給所有人。(圖)
** 我在今天講顯化過程，過去認為不可能的事情都要用顯化法則讓它實現，現在顯化事件，新亞特蘭提斯計劃透過顯化法則顯化新的世界和顯化事件。當我在部落格上公開一些指示的時候並不是隨意貼一篇文章。部落格上的每一個指示都是計劃的一個部份，不是隨便發一篇文章而已，在我部落格的主人不光是只有我而已，這個部落格代表7,000萬名抵抗運動成員。抵抗運動也會從更高的光明勢力接受指引。我們並不孤單並不孤獨，雖然戰役艱難但我們會贏得最後勝利。
** 感謝大家今天的蒞臨。感謝主辦人Jedi。
** 感謝他安排這場會議，謝謝大家也謝謝兩位口譯-Terry 和 Patrick。感謝所有來自世界各地的準備轉變團隊和所有的工作人員。感謝展示光能儀，感謝今天支持我們的龍族團體。
** 感謝抵抗運動，也感謝銀河聯盟，感謝愛希斯老師，她在她的國家幫助我們，感謝大家不辭辛勞參加這次會議。光的勝利。
** 感謝大家度過殊勝的禮拜天，大家在各地散播聖光。
** 
** 
** 2018.5
** 
** 顯化過程
** 顯化法則
** 今天我們要來講顯化過程。如果大家想要了解顯化過程這是一個很重要的關鍵，這是一個人生中很重要的一課，如果真的精通顯化法則跟顯化過程，那就可以重新掌握自己的人生了，那就可以自由的選擇人生中想要認識的人事物以及影響到地球的局勢。
** 我會用非常明確的方式來解釋顯化過程，我可以向大家保證，如果大家採取這些顯化步驟絕對能顯化出想要的結果。之前參加我們會議的人都有體驗過，他們都知道怎麼顯化。有沒有人自己善用顯化法則成功過的。
** 與會者顯化法則經歷分享:
** 與會者:去年我參加會議完想著如何使用顯化法則，我和一位有帕金森氏症的人合作，他說他身上有重要的使命，去年九月他下定決心說，他要治療好他的帕金森綜合症。我記得COBRA說顯化法則失敗原因是因為我們太早放棄了，因為我們看不到未來的結果。就在九月份，他下定決心的那一刻，他的朋友打電話聯絡到我，他開始講到地球解放之類的事情。
** 今年一月我就邀請這位帕金森氏症的朋友，邀到我的地方接受療癒，他之後就覺得身體好多了。
** 今年四月在我們裝了超光速粒子艙，他發出抉擇時當時我們還沒訂超光速粒子艙，在今年四月他躺完之後身體有很大的改變。我就知道改變是從你下定決心那一刻開始的，雖然看不到未來，但當你下定決心時命運巨輪就開始轉動了。
** 與會者:對於顯化法則我非常有體會了，我顯化大大小小無數次了。我的家人，我在2016年覺醒後非常…，我家裡人對我有影響，我擔心他們讓我有擔憂讓我沒辦法很好做我的使命，當時跟光明勢力求助，我聽冥想時……事情，1..2個月後出現一位我不認識的人，幫我解決我家人問題，我現在對我家人沒有後顧之憂了，所以抵抗運動招募我的話我隨時都可以走。
** 第一次聽到如意寶珠時，我就非常有感覺，我自己花了些錢買如意寶珠。我的工作在大陸各地出差，我就到處埋寶珠，我的薪水是固定的，不會有額外的收入，但是我花出去的錢很容易就回來了。
** 最重要的是我用了顯化法則才來到這裡，因為揚升會議是5/12~5/13號，我的工作在三月就安排一場工作會議在5/11~5/13號，也因此我就沒辦法參加會議，但當時我想參加5/16號的聚會，所以我就冥想祈請讓我來到台灣，然後在……號我收到通知我的工作取消了，所以我就提前來到了台灣。顯化法則非常好，只要專注意念就一定會顯化很快。
** COBRA:顯化法則就是這樣。
** 我現在向大家解釋顯化過程，大家要知道現在這個實體世界實相並不是固定不變的，我們現在實體世界看到的實相不過是能量世界發生的過程總和。地球上看到的每個人事物，都是在過去大家所有抉擇的總和。
** 現在會議場地一開始就是處於建築師裡面的想法，一開始在設計師和建築師腦袋裡構建出來，接著這個房子的高度跟法規都是所有人共同決定創造出來的。當這群人有最強大的願景跟顯化意念的時候，他就可以顯化出他想要的事物。如果你意念比老闆強，原本的工作就可以推掉然後來這場會議。
** 如果你想要做的事情符合聖光也符合光明勢力的旨意的話那這種結果會更容易顯化。我們每個想法跟意念都會在時空連續體裡產生漣漪，所以是意念塑造實相。
** 現在要講顯化法則。現在市面上寫著很多顯化法則(吸引力法則)的書，但這些書是不完整的內容，所以很多人會覺得練習顯化法則很挫折好像也沒什麼用，因為外面坊間教導的並不完整，現在我要跟大家講述完整的顯化法則。
** 我跟大家保證如果願意照著做絕對有效，這個是有物理根據的法則，如果我們按部就班執行顯化三步驟的話。我要來詳細解釋顯化法則三個步驟。
** 顯化法則第一個步驟是抉擇:
** 
** 抉擇是我們意志我是臨在的反射縮影，抉擇代表我們想要顯化還有我們想要創造的東西。
** 我在25歲的時候，當時我要顯化一個這樣的一個海水藍寶，現在他就在我身邊了，這就是一個很簡單的抉擇。抉擇是一個基於我們自由意志我是臨在的一個行動，當大家很清楚明確自己想要什麼的時候，你的抉擇才會明確。一個人有時會心猿意馬，決策過程當中，就是要整合不同面向的自我，將所有的面向整合為一。每個人都受到特定的編程，我們都受到編程認為我們需要或者想要什麼東西，但這些編程下的想法不代表是我們真正想要的東西。
** 我們講些例子:
** 
** 舉例來說有些人本身有藝術方面的才能，覺得我未來應該要去作畫。但問題來了，他的家族中祖父都是醫生，所以他爸爸希望他兒子去當醫生，所以當你住在這個家庭裡面，這個原本可能當藝術家的人最後卻當了醫生，很多人都希望子承父業，所以藝術家也會被迫去當醫生，可是這個人想去當藝術家。
** 最後你可能會去服從你父親的建議然後去學醫，可能這個人會認為這是他自己的決定，但是他內在有個聲音認為這不太對勁。你可能會顯化這個抉擇然後你決定學醫最後你變成了醫生，但你不會有快樂的生活，因為這不是基於你自由意志的選擇。
** 所以自由意志的意義在於你知道你真正想要什麼，然後付出行動。你的自由意志有時是和這個社會不一致的，這就看你去如何抉擇了。
** 第一階段攸關我們的抉擇，這時可以選擇隨波逐流跟著控制編程走，或者基於自由意志聽從高我的指引抉擇，這是每一天我們要做抉擇之前先做的選擇。
** 基本上這個社會的設置就是要讓我們不去聽從自由意志，這世界上有很多種規範來限制人類的行為和想法，怎麼穿、怎麼喝、怎麼吃，如果打破這些規則，社會大眾就會對你有強烈反應，這是非常巧妙的控制，變成人們會互相控制、互相約束。
** 所以控制矩陣不光是一小搓陰謀控制一大票人，控制矩陣也是人與人之間的互相控制。從某個層面來講，我們這300多人之間就在互相制約著，是否符合社會的規範。我知道這個控制矩陣的結構，我可以在15秒內說一句話惹毛大家，我知道這個控制編程是如何運作的，但是我不會去這麼做。每個人都在檢查身邊的人是否符合這些規範，控制矩陣會讓大家監視彼此，這是控制矩陣的基本結構。
** 如果想要使用顯化法則，我們首先要使用自己的自由意志，好比你一開始想要成為藝術家而不是醫生，那就開始學藝術，因為學習藝術是你自由意志的縮影，讓你可以過更快樂的人生。
** 這社會其中一個控制編程就是讓你認為當藝術家會餓死並且不會成功，但事實上藝術是沒有限制的，現在很多藝術家日進斗金賺數十億，因為這些藝術家他們相信這個世界是無限的，沒有限制的。
** 他們知道自由意志會打開一個無限豐盛的門戶，不管這個抉擇是大是小，這個抉擇都是通用的。事實上顯化1塊錢跟顯化10億美元都是同一個原理，顯化事件跟顯化一杯咖啡也是同一個原理。差別在於時間，越複雜的計劃越需要時間去顯化。
** 如果大家想了解自己的自由意志做出選擇，一定要先對自己誠實，所以要誠實的問自己我這一生到底要什麼，所以顯化法則第一步就是有明確的抉擇。當你對自己100%誠實，完全不在意社會對我們的眼光看法，所謂的小我的就會消散，因為小我這東西只不過是讓人們服從社會規範的概念而已。
** 當大家對於自己完全真誠，完全了解自己真心想要什麼的時候，你的抉擇和行動都會跟你的高我是一致的。執政官有非常強大的控制編程，這些控制編程讓人們覺得你的想法和慾望是自私的，這是一個非常強大的控制機制，也是非常強大的控制編程。
** 每個人的願望跟期望甚至是慾望都是我們人生的指南，這些可以讓我們更了解自己，其實我們人生中最夢幻的事情都與我們最崇高的使命是一致的，對於我們的慾望和期望，這些東西可以幫我們引導到最理想的生活。
** 我們的期望和慾望可能跟我們周遭的大環境跟社會不太相符。這些想法和我們的慾望也代表我們有辦法在控制矩陣打開一道裂縫，那個時候也代表我們可以實踐自己的使命，所以顯化法則第一個步驟是要先有明確的抉擇。
**  
** 
** 顯化法則的第二步驟是祈請:
** 
** 祈請意思就是使用我們情緒的力量，將我們想要的東西下定決心吸引到我們身邊。首先要有抉擇，我們要用所有熱心渴望來吸引我們的抉擇、我們想要的東西。我們這股強大的情緒會在身邊形成強大的漩渦場，這股漩渦能量場可以把我們下決心想要的東西引到我們身邊。
** 祈請也代表可以呼請光明勢力幫助我們顯化，我們可以用祈請、用禱告、也可以用冥想或者觀想，也可以呼請光明勢力、呼請天使、呼請揚升大師們來幫助我們的顯化。
** 顯化法則的第三步驟就是具體的行動:
** 
** 具體行動不代表我們要拚死拚活的努力工作，我說的具體行動是一個投入熱情而且按部就班的行動，只要用正確方法來做的話，具體行動上可以非常輕鬆和順利。
** 如果大家一直重複使用這三個顯化法則三步驟，大家把顯化法則當電腦程式一樣按步就班反覆使用的話，我向大家保證你絕對可以顯化你想要的東西。
** 我剛剛說過，顯化法則其中的最主要一個問題就是有些人太早就放棄了，實體世界並不是一個能量很流動的世界，算是一個有點僵化的世界，這就是為什麼顯化要花一段時間的原因，顯化法則不是一瞬間就能發生的事情，需要一些時間來顯化。
** 所以我們需要不斷的反覆使用顯化法則直到我們想要的東西顯化的那一天。如果我們現在需要一杯咖啡只需要五分鐘，顯化一間新房子可能要花五年，顯化出事件可能要十年，這些顯化都需要花些時間來完成。
** 如果想要顯化一間新房子，但在顯化過程的第三年就放棄了，那這樣就是在浪費時間，如果你的顯化堅持了五年，那麼你就可以換到你想要的新房子了。所以關鍵就是絕對絕對不要放棄，堅持再堅持。
** 當你完全跟你的自由意志以及高我靈魂合一的時候，你等於是在改變地球控制矩陣的結構。我們是被選上的一群人，我們這群人要把新的實相帶入這個地表世界，所以我們的顯化過程也等於正在改變整個地球社會。
** 我來說一個顯化的例子。18世紀時羅斯柴爾德家族決定在地球創建新世界秩序，羅斯柴爾德知道這項計劃必須要花200年的時間，羅斯柴爾德知道他們沒辦法活到計劃實現的那一天，可是他們決定要用這一生實現這個計劃甚至把這些計劃傳承給他們的兒子跟孫子。我們現在的金融系統是羅斯柴爾德家族花費250年精心打造的結果，如果我們想要創造新的金融體系就要跟羅斯柴爾德一樣的投入和用心。
** 我們不需要花250年，這一次我們可能花比較少時間，大家願不願意花5~10年，我們不會花費250年，我們會讓它更快顯化，我們不需要花費那麼多時間，你準備好用1年、5年或者20年的努力來顯化它嗎，是還是不是？
** 我們的計劃一定會比他們成功，我們的計劃是跟神聖計劃相關的，我們想要的是全世界所有人的豐盛，而不只是一小群權貴人士的豐盛。有一個非常強大的光明勢力在支持我們的計劃。
** 在光之工作者的圈子裡面，要實現顯化問題是人與人之間的關係。光之工作者之間經常發生衝突，光之工作者之間的衝突阻礙了正面的人際關係顯化，這也是我們建立新社會的主要障礙。所以我會在今天下午講述關於新人際關係的事情。
** 所以顯化法則就是一直重複剛剛我所說的三個顯化步驟，如果大家重複使用這個顯化法則的話一定會顯化出來，使用這個顯化法則沒有限制，大家越是相信，顯化成功的可能性就越大。大家不要限制自己能顯化的東西，因為任何事情都是只要花時間就一定會顯化。
** 問答時間:
** 與會者:我現在跟一些具有合一意識的夥伴顯化一個大團結不再有分裂跟紛爭，我們也試著溝通跟努力，最近會做很多動作讓我們在華人社區有更多團結，最近燕妮嘗試用扭曲揚升會議、扭曲抵抗運動招募內容，遇到一些比較棘手的問題，也跟一些群組不要有衝突，Cobra你是否有解決這個問題的更好的方式？
** Cobra:我不對她發表任何評論。下午時我會講更多關於新社區的內容。這應該是這些衝突的解決方法。
** 與會者:每個人都有自由意志，我想顯化的事情跟對方想顯化的東西產生衝突該怎麼辦?
** COBRA:如果你的抉擇符合你的高我旨意就會顯化，其他人的自由意志也不得不跟著最高實相去調整，符合更崇高的實相的抉擇會被顯化出來，基本上這就是我們的社會演變和進化的過程。
** 與會者:我們在新時代運動觀念裡認為人跟人的互動是基於頻率，面對生活中負面的人事物，這些是不是自己內在投射而顯化發生的實相?
** COBRA:基本上我們內在的弱點都是外在干擾對你的攻擊點，我們應該要做的就是對這些外在的干擾說「不」，我會在下午實相過濾說明更清楚一些，感謝大家。
**  
** 
** 心想事成/達成豐盛的技術
** 有些很強大的光之存有，他們會支持我們的顯化過程，其中一位最重要的光之存有就是聖哲曼，聖哲曼的計劃就是教導人們如何使用顯化法則，他也希望教導人們可以顯化充滿豐盛的新時代，如果大家希望自己的顯化過程更快更輕鬆的話就可以呼請聖哲曼的臨在，他會支持我們的顯化。
** 顯化法則有一些很高深的技術，我會在這講幾個進階的顯化技術，其中一個技巧叫做實相塑造法，實相塑造法是一個基於我是臨在的神聖意志，實相塑造法是塑造我們人生實相的強大工具。
** 
** 這個圖表可以解釋天地萬物的顯化過程，這是一個我昨天有講過的雙撓場螺旋結構，這是這個宇宙神聖幾何構造。
** 我有講過所有實體世界顯化出來的東西都是源自高維度靈性世界的想法，我們一開始想要顯化的東西都是一個想法和抉擇，這個抉擇會形成一個顯化漩渦，然後這個顯化漩渦會經過我們的光體門戶來到實體世界。
** 如果大家知道這個原理，大家就可以用自己的專注來顯化自己想要的事情，大家把注意力放在一個地方就可以打開一個門戶進而顯化自己想要的人事物。如果我很集中的想一個麥克風，盯著這個麥克風15分鐘我就可以在我人生中顯化出更多的麥克風。
** 也可以用注意力來顯化類似的事物，如果大家想要顯化豐盛，大家應該要做什麼呢，就是買一枚金幣放在自己口袋裡面每天拿出來看一下，大家每一次專注看著這枚金幣就會開啟一個門戶，這門戶就會吸引很多的金幣，如果覺得金幣太貴的話也可以買銀幣，買一枚銀幣一樣放進自己的口袋裡。
** 一枚銀幣價錢差不多跟一個大披薩差不多，大家應該都能有足夠的收入購買一枚銀幣。記得去年有個參與會議的人說他用了一個銀幣當錢母，結果他之後多賺了兩百多枚銀幣，所以這個方法真的管用。
** 如果想要顯化一棟房子，可以買一個小模型屋放在自己的口袋裡面，大家每天就可以從口袋拿出模型屋出來看，每天看，這個專注力就會開啟門戶讓你顯化出你自己想要的房子，大家真的不用擔心，這是很有效的技巧，這個模型屋的樣子就會和你理想中的房子是一樣的。
** 如果大家不小心買錯房子模型整天看的話，那可能就會顯化出不同的房子了，這顯化技巧是非常具體精確的。
** 我之前就有買一個模型來顯化的經驗，我顯化出來的東西跟我買的模型是一模一樣的，所以買來的模型要盡量具體符合自己想要的。
** 
** 在場有沒有人會藝術能夠做個壓縮突破的模型?我們請他幫我們顯化事件。
** 我現在有個任務要交給你，請把壓縮突破的模型做成3D列印的樣子
** COBRA:你要做的模型大小差不多是….，可以放在每週實體聚會上面，大家聚會時就盯著模型看，大家都盯著模型看5~10分鐘。
** 與會者:這樣的花費會比較昂貴。
** COBRA:可以找團隊，找Jedi解決。
** 如果大家想要顯化一個東西，最好的辦法就是做一個縮小版的模型。如果大家想要太空旅行的話那麼最好在家裡買一個太空船的模型，這是一個非常具體的顯化技巧。
** 我們來講下一個技巧。我們可以做一個夢想地圖，這個地圖可以引導我們過著理想的人生。現在請大家拿出一張紙，請大家開始畫畫，來畫你認為的理想人生，用你的想像力畫出你想像的人生，完全沒有限制，想畫什麼就畫什麼。
** 慢慢的放下筆
**  
** 
** 大家剛剛畫的這張圖就是各位的夢想地圖，大家的實相就會跟著這張夢想地圖跟著改變，這是一個非常強大的顯化技巧。不光只是圖畫而已，我在30年前做了一張人生中第一張夢想地圖，10年後我在30年前畫的夢想地圖有80%都實現了。接著我開始畫了第二張夢想地圖，我到現在還在使用這張地圖顯化。現在這張地圖我已經進行了很多顯化，我在地圖上畫任何我想要的東西，即使只是小事情，這是非常強大的顯化技巧。
** 大家最好回家畫一張更精確、更好的地圖，大家可以回家拿全開的紙張畫一幅更完整的夢想地圖，大家可以把自己的夢想地圖畫在牆壁上，有空時就可以看一下。
**  
** 
** 現在做一個簡單的豐盛冥想:
** 將金黃閃耀的光吸進自己的身體
** 
** 將金黃閃耀的光發送到四面八方
** 保持幾分鐘時間
** 深呼吸將身體充滿更多金黃閃耀的光
** 
** 這道金黃閃耀的光滲透到身體裡所有細胞，充滿我們能量場
** 
** 觀想自己化為一道金黃閃耀的光柱
** 
** 在此呼請聖哲曼大師的臨在
** 
** 幫助大家顯化個人、親朋好友、以及好人的豐盛
** 
** 觀想心輪發出金黃閃耀的漩渦、漩渦不斷擴展
** 
** 觀想金黃閃耀的漩渦吸引豐盛、吸引了黃金跟金錢還有房地產還有美好的車子還有最理想的人生
** 
** 觀想一切美好的事物來到自己的人生
** 
** 花一段時間觀想金黃閃耀的漩渦吸引一切美好的人事物
** 
** 觀想聖哲曼大師放了一枚大金幣在我們手上
** 
** 感受大金幣的重量跟手感，感覺自己手指上的大金幣，這是大家的錢母
** 
** 大家感覺一下手上的這一枚錢母
** 
** 從現在起可以把這個錢母放在口袋裡隨身攜帶
** 如果大家還沒有錢母，那麼現在下定決心去買一枚金幣/銀幣然後把這枚錢母放在口袋裡，這枚錢母從現在開始會替我們顯化豐盛，聖哲曼大師會加持並且祝福你的決定，他會從現在開始幫助你顯化豐盛。
** 感覺所有的金光都停留在這個當下，感覺自己已經下定決心要買一枚錢母(金幣/銀幣)。感覺手上的這一枚金幣，現在慢慢的開始將意識帶回自己身體。
** 歡迎大家回來
**  
** 
** 顯化過濾法
** 關於顯化過程我要講一個重要事情，(圖-生命之花)剛剛我跟大家說過要怎麼顯化自己想要的重要東西，但人生中也會碰到我們不想要的事情，而你已經把這些不想要的東西作為你決定的一部分去接受了，其實有一個很簡單的方法可以幫助我們清除人生中的負面人事物，這種做法叫做顯化逆轉法，也叫實相過濾法。
** 顯化逆轉法就是一個抉擇，這個抉擇就是不論在任何場合，你再也不會接受某一類人事物出現在你的人生當中。如果人生中出現各種霸凌狀況，只要下定決心這種霸凌就會停止。如果上班每天被老闆罵，那只要下一個明確的抉擇，老闆就不會罵你了。
** 如果你經常遇到某個人的負面行為，你只要下一個明確的抉擇，顯化逆轉法就可以幫助你擋住那個人的負面行為，我們整體來說人類就是在做一個實相逆轉，我們正在逆轉有陰謀集團存在的實相，我們要移除陰謀集團。
** 如果有144,000(臨界質量)的人一起做實相逆轉法的話，陰謀集團就會從此消失。
** 可惜現在大約只有3萬人下定決心要移除陰謀集團，基於這個原因陰謀集團的移除過程要花比較多時間。
** 大家有沒有這方面心得要分享的
** 與會者:我為了要參加會議，同時在2個餐廳做兼職工作，第一個老闆人不錯，但是說話很直接，我就用顯化法則跟龍族守護冥想，發現他跟我接近時的氣場就比較溫柔，我也做女神旋渦。另一個老闆娘也是對我很兇，我回家後做龍族守護冥想結果那老闆娘回家就生病了。
** 另一個做晚班的工作，當時有點累就在想可不可以祈請光明勢力讓餐廳客人早點回家不要太多人，結果8..9點後就沒什麼人了，老闆娘就叫我可以提早回家休息了。
** COBRA:所以顯化法則是用於人生當中每件大小事，當大家想要對任何事情說「不」的時候都可以用顯化逆轉法。大家想要說「是」的話使用顯化法則，想說「不」的時候使用顯化逆轉法。這個時候就是自己在運用自由意志的時刻，今天早上會議到此結束告一段落。
** 待會要接受點化的人一點半前來前排集合，其他人三點見。
