* Ver. 20190719 
1. 实相塑造法基本完成
2. 实相过滤法基本完成
3. 彩虹旋涡支持场基本完成
4. 问答部分基本完成
5. 祈请部分基本完成
6. 行动部分基本完成
7. 重复部分基本完成
* 精简版
** 所有实体世界显化出来的东西都是源自高维灵性世界的想法，我们一开始想要显化的东西都是一个想法和抉择，这个抉择会形成一个显化漩涡，然后这个显化漩涡会经过我们的光体门户来到实体世界。
** 大家可以用自己的专注来显化自己想要的事情，大家把注意力放在一个地方就可以打开一个门户进而显化自己想要的人事物。
** 实体化模型
*** 如果想要显化一栋房子，可以买一个小模型屋放在自己的口袋里面，大家每天就可以从口袋拿出模型屋出来看，每天看，这个专注力就会开启门户让你显化出你自己想要的房子，大家真的不用担心，这是很有效的技巧，这个模型屋的样子就会和你理想中的房子是一样的。
*** 如果大家不小心买错房子模型整天看的话那可能就会显化出不同的房子了，这显化技巧是非常具体精确的。所以买来的模型要尽量具体符合自己想要的。
*** 我们可以做一个压缩突破模型放在每周实体聚会上面，大家聚会时就盯着模型看，大家都盯着模型看5~10分钟。
*** 如果大家想要显化一个东西，最好的办法就是做一个缩小版的模型。如果大家想要太空旅行的话那么最好在家里买一个宇宙飞船玤的模型，这是一个非常具体的显化技巧。
*** 现在我们已经做出了压缩突破的模型图片，大家可以使用这些图片去制作出压缩突破的实体模型，也可以做其它的显化用途上，这张压缩突破模型图片已经经过COBRA的确认，大家可以广为宣传使用。
** 对自己诚实，绝对诚实
*** 我们必须对自己保持绝对诚实并在我们的生活中拥有足够的觉知去看我们是如何以及因何作出我们正在做出的那些选择的。否则的话我们的抉择会失真，我们的生活会偏离我们真正的目标。
*** 一个相关例子是假设一个人想要获得来自其父亲的认可，因此选择了医学，接着成为医生这条道路。终于在晚些时候他意识到他想做一些完全不同的事情，一些他的心起初就真正想做的事情。
*** 恐惧可以歪曲我们去看和选择我们真正想要显化的事物的力量。
*** 这种恐惧只在缺乏对自己的诚实的情况下出现。
** 显化法则有三个简单的步骤：
*** （1）抉择
*** （2）意志/呼请
*** （3）行动。
*** 每个思想和行动都会在无限的意识场域中创造出涟漪。我们比我们意识到的更加强大。
*** 那些有着最强的与我是临在的连结的人知道这个真理。我们的我是临在正放射着我们信念的能量。
*** 我们的思想以特定的频率过滤这股能量，接着这股能量滤过我们的情绪并最终显化为物质实相。
*** 我们的信念可以改变世界。
*** 我们正在这个星球上塑造着实相并且我们有强大的力量在协助我们——在天上以及地下。所以别害怕请求你真心想要的。圣哲曼说呼请然后你就会接收到。
*** 来自于我是临在的抉择是更加强大有效的。我们必须如水晶般清晰并坚持我们想要的，不要摇摆不定。花点时间明确自己是值得的。
*** 阴谋集团通过让我们认为知道自己想要什么并去追求它是自私的来误导我们。事件之后，显化会更加迅速地发生，在五维是即刻的。
*** 呼请与意志涉及到使用我们的情感、想象和可视化来填充能量流，深入到我们想要的事物的细节。带着期待，但别沉迷于它，将其放下。然后无论如何，不放弃我们真心渴望的。
*** 罗斯柴尔德知道这个并坚持了70年无论事情变得对他们来说有多困难。
*** 行动就是根据你先前的抉择和呼请作出你被指引去做的行为，带着一种你渴望的已经显化的那股能量的体验去做，就像细胞语言一般。
** 显化逆转法
*** 我们可以显化，同样也可以反显化。只要简单地宣告“我不想要”我们生活中可能存在的许多我们不喜欢的事情，之所以存在就是因为我们没有作出对它们说不的决定。
*** 我们有简单地直接离开某人或拒绝见他们的能力。我们可以在我们自己的环境-财产，家庭，关系等等中开始实践这一点，并将其扩展到整个行星层面。
*** 144000人对阴谋集团说“不”将导致压缩突破。我们必须做出这个决定并保持专注。
** 实相塑造
*** 实相总是在持续地显化并在一个连贯的能量流中被创造出来。
*** 如果我们认出在生活中起作用的部分并感激我们已经拥有的，我们就可以将这股显化之流扩展并创造我们想要的。注意这股能量的流动并拥有感激之心，我们显化的力量就会增强。
*** 如果我们注意到事物的同步性，我们同样也能看出我们是如何与这股能量流连结在一起并经历实相的塑造的。
*** 同样地，使用内在指引也会培养这个能力。愿意持续和坚持采取行动来朝向自己渴望的实相，以及脱离舒适区。
*** 要有意愿通过物理的经验（不带评判地）周遭和内在增强的能量场域来扩展它.
*** 同样地通过创造更高的目标和扩展我们的信念我们就可以扩展实相的球体。
*** 接着柯博拉指导我们用一个非常物理的方式来协助我们自身的显化过程（之前他要求我们带杂志、大报纸、剪刀和胶水到课上）。我们分成小组，分享自己带的这些资源。
*** 他要求我们将杂志中符合我们想要显化的事物的图片剪出来，接着当我们有了足够的图片，就把它们粘贴在每个大报纸上。
*** 他给予我们足够的时间来做这个，这很有趣并协助我为整体进行考量的过程。
*** 我发现和剪出的图片很接近我心中渴望的事物。当我将它们都粘连在一起时，这创造出一个有力的可视化。
*** 之后柯博拉说我们可以观想我们的图片像一个在漩涡中旋转的朝向我们的能量场域。
*** 我们可以对自己重复道“我的我是临在正在创造一个与行星交流的能量漩涡并吸引我想要的已创造和正在创造的情境到我的生活中。
*** 显化 级别：专家
* 整合版
** 显化法则的原理
*** 基本上每个人的我是临在都会发送能量波到我们生活的第三维度世界，我是临在连结最强的人就可以决定地球的实相。只要有一个人跟我是临在有完美的连结，只要一个人就能解放地球。我是临在祂会将祂的能量波发送到第七维度和七维以下所有的世界，这种能量波会经过很多层的过滤来到我们的现实世界。
*** 简单说一下。我是临在会发送自己的能量波，接著我们的心智层和情绪层会把我是临在的能量波转换成一种频率，接著往下降到情绪体，接著来自情绪体的能量再次沉降进来来到我们的现实生活。我们生活周遭就像是一层层能量过滤的结果。这就是我是临在显化实相的方法。现在说些细节。
*** 每个人是无极限的，人是无极限的。宇宙中并没有什麽是自然法则规范让我们不能显化的东西，你可以显化任何的东西。科学家都说这个不可能、那个不可能，他们说自由能源不可能，他们说光速应该是宇宙最快的速度。这是因为科学家的知识和眼界被阴谋集团打压，阴谋集团用负面科技打压人类的眼界，他们想塑造一个到处都有限制和控制的世界，阴谋集团他们本身就了解显化法则，这就是他们为何如此成功地控制这个世界，
*** 我会简单的说明向大家说明显化法则。身体有肉体、情绪体、心智体，有办法让肉体、心智体、情绪体统合到一致频率，我们就一定会成功。
*** 如果精通显化法则跟显化过程，那就可以重新掌握自己的人生，就可以自由的选择人生中想要认识的人事物以及影响到地球的局势。
*** 与会者显化法则经历分享:
**** 与会者:
***** 去年我参加会议完想著如何使用显化法则，我和一位有帕金森氏症的人合作，他说他身上有重要的使命，去年九月他下定决心说，他要治疗好他的帕金森综合症。我记得COBRA说显化法则失败原因是因为我们太早放弃了，因为我们看不到未来的结果。就在九月份，他下定决心的那一刻，他的朋友打电话联络到我，他开始讲到地球解放之类的事情。
***** 今年一月我就邀请这位帕金森氏症的朋友，邀到我的地方接受疗癒，他之后就觉得身体好多了。
***** 今年四月在我们装了超光速粒子舱，他发出抉择时当时我们还没订超光速粒子舱，在今年四月他躺完之后身体有很大的改变。我就知道改变是从你下定决心那一刻开始的，虽然看不到未来，但当你下定决心时命运巨轮就开始转动了。
**** 与会者:
***** 对于显化法则我非常有体会了，我显化大大小小无数次了。我的家人，我在2016年觉醒后非常…，我家裡人对我有影响，我担心他们让我有担忧让我没办法很好做我的使命，当时跟光明势力求助，我听冥想时……事情，1..2个月后出现一位我不认识的人，帮我解决我家人问题，我现在对我家人没有后顾之忧了，所以抵抗运动招募我的话我随时都可以走。
***** 第一次听到如意宝珠时，我就非常有感觉，我自己花了些钱买如意宝珠。我的工作在大陆各地出差，我就到处埋宝珠，我的薪水是固定的，不会有额外的收入，但是我花出去的钱很容易就回来了。
***** 最重要的是我用了显化法则才来到这裡，因为扬升会议是5/12~5/13号，我的工作在三月就安排一场工作会议在5/11~5/13号，也因此我就没办法参加会议，但当时我想参加5/16号的聚会，所以我就冥想祈请让我来到台湾，然后在……号我收到通知我的工作取消了，所以我就提前来到了台湾。显化法则非常好，只要专注意念就一定会显化很快。
*** 要知道现在这个实体世界实相并不是固定不变的，我们现在实体世界看到的实相不过是能量世界发生的过程总和。地球上看到的每个人事物，都是在过去大家所有抉择的总和。
*** 现在会议场地一开始就是处于建筑师裡面的想法，一开始在设计师和建筑师脑袋裡构建出来，接著这个房子的高度跟法规都是所有人共同决定创造出来的。当这群人有最强大的愿景跟显化意念的时候，他就可以显化出他想要的事物。如果你意念比老闆强，原本的工作就可以推掉然后来这场会议。
*** 如果你想要做的事情符合圣光也符合光明势力的旨意的话那这种结果会更容易显化。我们每个想法跟意念都会在时空连续体裡产生涟漪，所以是意念塑造实相。
*** 现在要讲显化法则。现在市面上写著很多显化法则(吸引力法则)的书，但这些书是不完整的内容，所以很多人会觉得练习显化法则很挫折好像也没什麽用，因为外面坊间教导的并不完整，现在我要跟大家讲述完整的显化法则。
** 第一步：抉择
*** 抉择第一步是要很清楚知道自己要什麽东西
*** 所有显化事物的法则就是依循三个步骤，我会很细节的跟大家说，做些实际的练习，所以第一步是抉择，人们很容易脑袋一团乱，有著各种愿望和想法及专案想要完成。
*** 有时会听从父母的抉择去做他们想要我们做的事情以及想要我们唸的学校，之后会发现都不是我们自己真正想要的。人心很容易因为各种期望和愿望而被迷惑，所以显化法则第一步要很清楚知道自己要的是什麽，如果完全不知道自己想要的是什麽，那麽显化出来的只是一团迷惑。
*** 每天花5分钟去了解自己想要显化什麽，每天花5分钟就可以避免自己浪费人生。只要很清楚自己人生目标就能知道对于自己来说什麽才是最重要的。阴谋集团他们做的事情让我们内心天人交战，让我们不知道要做什麽，所以阴谋集团一直想让我们处于迷惘状态。
*** 有时要让自己独处，让自己能够思考我这一生想要什麽。很多心智编程会阻止人们了解自己人生的真正目标。我说一些让大家了解一下。
*** 有些心智编程会影响显化能力。第一个是了解自己人生想要什麽是很自私的想法。如果为自己追求某种东西是很不灵性的行为，有很多洗脑教条都是这样跟你讲的。我会说:你的人生想法期望和启发是来自我是临在对你呼喊的缩影。
*** 好比说现在有很强烈的指引告诉你想去南极洲，那可能是我是临在告诉你想去南极洲。这些想法背后是有原因的。如果了解显化法则的作法那就真的有办法去到南极洲，抉择就是关键。
*** 抉择并不是只要5分钟就会变的东西，显化法则要成功，前提是抉择要一直不变，只要大家很清楚自己的抉择，基本上是不会变的，可能会有些变化，但重要的大方向是不会改变的，因为你真的很清楚你要什麽，你的抉择就是反应我是临在对你的诉求。
*** 很重要的是坚持再坚持绝对不要放弃，不管是遇到了什麽阻碍，不管别人怎麽说，永远永远不要放弃。
*** 很多人会抱怨显化法则不成功是因为他们一下子就放弃了，他们可能距离成功就只有临门一脚，但却在成功前就放弃了。显化法则不光是要显化出金钱而是要显化出我是临在的神圣意志。金钱只是一个工具，而我们要用这个工具(金钱)在这世界显化出我是临在的神圣意志。
*** 参宿七的黑暗势力在5,000年前引进了金钱奴役制度到地球上，但我们还是可以将金钱转换成神圣工具完成理想的崇高目标，我们仍然可以用金钱显化我是临在的神圣意志。
*** 你的抉择就反应出来自我是临在的意志，当你完全理解自己的时候。其实认识自我很简单并不複杂，我们不要自欺欺人不要骗自己，对自己完全的诚实，如果真的很讨厌一个人就让自己承认自己讨厌那个人，这样你才有办法转换这个恨意。如果不承认自己的想法，这些情绪就会一直堆积在那边。
*** 有些人会做些错误的抉择隐藏一些事物，或者操弄某些事物或做些很奇怪的事情。有些人所做的抉择是为了得到父亲/母亲的认同，有些人并不想去唸医学院，他们只想为了得到父亲/母亲的认同而去唸了医学院，他们浪费了五年的时间学医，他可能会变成很厉害的医师，有著精湛的医术，但那个时候他就像行尸走肉一样每天工作8小时，当初只是为了完成父亲/母亲的期望。
*** 他如果懂得显化法则，他其实可以告诉自己真正的想法来得到父亲的认同，那该怎麽做?其实他会发现只需要跟父亲花几个月时间沟通他就会认同我了，这样他就可以改行去做艺术家。
*** 这是一个来自我是临在的正确抉择和其它错误愿望之间的差别，大家只要对自己诚实的话就会知道我再说什麽了。这个案例够清楚真实了。
*** 有时对自己不诚实的人会很恐惧，恐惧只会在你对自己不诚实的时候变得强大，只要很了解自己是谁就不会恐惧。阴谋集团没有能力控制你，只要对自己诚实了解自己是谁，阴谋集团就不能威胁你也不能恐吓你，因为你的我是临在凌驾所有一切。所以只要你的意志够清楚强大，将是宇宙中最强大的力量。因为你的意志显化了我是临在的神圣意志，祂会自行显化。
*** 这时候意志就反应出我是临在的神圣意志。
*** 第一步:你不会放弃，你很清楚了解自己的抉择就会反应出我是临在的神圣意志。
*** 关于第一步的抉择还要说些事情，关于抉择的事情刚刚忘了说了，抉择要尽可能的精确明确，抉择要很具体。有些人可能只想要新车，抉择要更具体一点，什麽样的具体呢?如果我要一台车，我会说:我要一台全新的捷豹跑车。车上要有GPS导航、涡轮增压还附加所有顶级配备。
*** 有些人说:我想要第一次接触、我想跟星际兄弟姊妹见面。那麽我应该要具体一点。好比说:我要昴宿星人在我家的后院降落。他们会跟我见面；邀约我进入飞船畅谈10分钟。抉择越具体、目标越明确，就不会有些模糊不清的问题。
*** 只要抓到各种精确细节就放到自己情绪和观想画面裡，不过有时会有些变化，有些细节好比那台捷豹可能是从金属色或变白色，这只是小细节还好。如果真的完全精通显化法则，可以显化到每个目标的细节。精准的程度会让人吓一下。惊叹:这根本就是我想要的东西。
*** 有了明确的画面就可以关注在那个画面，但不要变成迷恋和痴迷了。一旦很清楚显化法则，目标一定会实现。但人生一样要往前迈进，不是说要说服自己，祈请是显化法则的一部份，所以就一直的观想成天在观想，不是说这是显化法则的一部份就踟蹰不前。只要很清楚是显化的一部份，显化法则就一定会成功。把抉择愿望先放心裡然后过好每一天，
*** 抉择是我们意志我是临在的反射缩影，抉择代表我们想要显化还有我们想要创造的东西。
*** 抉择是一个基于我们自由意志我是临在的一个行动，当大家很清楚明确自己想要什麽的时候，你的抉择才会明确。一个人有时会心猿意马，决策过程当中，就是要整合不同面向的自我，将所有的面向整合为一。每个人都受到特定的编程，我们都受到编程认为我们需要或者想要什麽东西，但这些编程下的想法不代表是我们真正想要的东西。
*** 我们讲些例子:
*** 举例来说有些人本身有艺术方面的才能，觉得我未来应该要去作画。但问题来了，他的家族中祖父都是医生，所以他爸爸希望他儿子去当医生，所以当你住在这个家庭裡面，这个原本可能当艺术家的人最后却当了医生，很多人都希望子承父业，所以艺术家也会被迫去当医生，可是这个人想去当艺术家。
*** 最后你可能会去服从你父亲的建议然后去学医，可能这个人会认为这是他自己的决定，但是他内在有个声音认为这不太对劲。你可能会显化这个抉择然后你决定学医最后你变成了医生，但你不会有快乐的生活，因为这不是基于你自由意志的选择。
*** 所以自由意志的意义在于你知道你真正想要什麽，然后付出行动。你的自由意志有时是和这个社会不一致的，这就看你去如何抉择了。
*** 第一阶段攸关我们的抉择，这时可以选择随波逐流跟著控制编程走，或者基于自由意志听从高我的指引抉择，这是每一天我们要做抉择之前先做的选择。
*** 基本上这个社会的设置就是要让我们不去听从自由意志，这世界上有很多种规范来限制人类的行为和想法，怎麽穿、怎麽喝、怎麽吃，如果打破这些规则，社会大众就会对你有强烈反应，这是非常巧妙的控制，变成人们会互相控制、互相约束。
*** 所以控制矩阵不光是一小搓阴谋控制一大票人，控制矩阵也是人与人之间的互相控制。从某个层面来讲，我们这300多人之间就在互相制约著，是否符合社会的规范。我知道这个控制矩阵的结构，我可以在15秒内说一句话惹毛大家，我知道这个控制编程是如何运作的，但是我不会去这麽做。每个人都在检查身边的人是否符合这些规范，控制矩阵会让大家监视彼此，这是控制矩阵的基本结构。
*** 如果想要使用显化法则，我们首先要使用自己的自由意志，好比你一开始想要成为艺术家而不是医生，那就开始学艺术，因为学习艺术是你自由意志的缩影，让你可以过更快乐的人生。
*** 这社会其中一个控制编程就是让你认为当艺术家会饿死并且不会成功，但事实上艺术是没有限制的，现在很多艺术家日进斗金赚数十亿，因为这些艺术家他们相信这个世界是无限的，没有限制的。
*** 他们知道自由意志会打开一个无限丰盛的门户，不管这个抉择是大是小，这个抉择都是通用的。事实上显化1块钱跟显化10亿美元都是同一个原理，显化事件跟显化一杯咖啡也是同一个原理。差别在于时间，越複杂的计划越需要时间去显化。
*** 如果大家想了解自己的自由意志做出选择，一定要先对自己诚实，所以要诚实的问自己我这一生到底要什麽，所以显化法则第一步就是有明确的抉择。当你对自己100%诚实，完全不在意社会对我们的眼光看法，所谓的小我的就会消散，因为小我这东西只不过是让人们服从社会规范的概念而已。
*** 当大家对于自己完全真诚，完全了解自己真心想要什麽的时候，你的抉择和行动都会跟你的高我是一致的。执政官有非常强大的控制编程，这些控制编程让人们觉得你的想法和慾望是自私的，这是一个非常强大的控制机制，也是非常强大的控制编程。
*** 每个人的愿望跟期望甚至是慾望都是我们人生的指南，这些可以让我们更了解自己，其实我们人生中最梦幻的事情都与我们最崇高的使命是一致的，对于我们的慾望和期望，这些东西可以帮我们引导到最理想的生活。
*** 我们的期望和慾望可能跟我们周遭的大环境跟社会不太相符。这些想法和我们的慾望也代表我们有办法在控制矩阵打开一道裂缝，那个时候也代表我们可以实践自己的使命，所以显化法则第一个步骤是要先有明确的抉择。
*** 我刚刚说过，显化法则其中的最主要一个问题就是有些人太早就放弃了，实体世界并不是一个能量很流动的世界，算是一个有点僵化的世界，这就是为什麽显化要花一段时间的原因，显化法则不是一瞬间就能发生的事情，需要一些时间来显化。
*** 所以我们需要不断的反覆使用显化法则直到我们想要的东西显化的那一天。如果我们现在需要一杯咖啡只需要五分钟，显化一间新房子可能要花五年，显化出事件可能要十年，这些显化都需要花些时间来完成。
*** 如果想要显化一间新房子，但在显化过程的第三年就放弃了，那这样就是在浪费时间，如果你的显化坚持了五年，那麽你就可以换到你想要的新房子了。所以关键就是绝对绝对不要放弃，坚持再坚持。
*** 当你完全跟你的自由意志以及高我灵魂合一的时候，你等于是在改变地球控制矩阵的结构。我们是被选上的一群人，我们这群人要把新的实相带入这个地表世界，所以我们的显化过程也等于正在改变整个地球社会。
*** 我来说一个显化的例子。18世纪时罗斯柴尔德家族决定在地球创建新世界秩序，罗斯柴尔德知道这项计划必须要花200年的时间，罗斯柴尔德知道他们没办法活到计划实现的那一天，可是他们决定要用这一生实现这个计划甚至把这些计划传承给他们的儿子跟孙子。我们现在的金融系统是罗斯柴尔德家族花费250年精心打造的结果，如果我们想要创造新的金融体系就要跟罗斯柴尔德一样的投入和用心。
*** 我们不需要花250年，这一次我们可能花比较少时间，大家愿不愿意花5~10年，我们不会花费250年，我们会让它更快显化，我们不需要花费那麽多时间，你准备好用1年、5年或者20年的努力来显化它吗，是还是不是？
*** 我们的计划一定会比他们成功，我们的计划是跟神圣计划相关的，我们想要的是全世界所有人的丰盛，而不只是一小群权贵人士的丰盛。有一个非常强大的光明势力在支持我们的计划。
*** 在光之工作者的圈子裡面，要实现显化问题是人与人之间的关係。光之工作者之间经常发生衝突，光之工作者之间的衝突阻碍了正面的人际关係显化，这也是我们建立新社会的主要障碍。所以我会在今天下午讲述关于新人际关係的事情。
*** 所以显化法则就是一直重複刚刚我所说的三个显化步骤，如果大家重複使用这个显化法则的话一定会显化出来，使用这个显化法则没有限制，大家越是相信，显化成功的可能性就越大。大家不要限制自己能显化的东西，因为任何事情都是只要花时间就一定会显化。
** 第二步：祈请
*** 祈请意思就是使用情绪的力量，下定决心将想要的东西吸引到我们身边。我们要用所有热心渴望来吸引我们的抉择，用情绪吸引帮助显化的各种人事物。
*** 一旦有明确的意志就会和我是临在建立清楚的能量管道，接著用情绪加速催化这股能量流。
*** 我们可以祈请、祷告、冥想、观想或假装看到了要显化的目标。也可以用情绪呼请光明势力帮助自己想显化的事物，可以呼请天使、呼请龙族、呼请抵抗运动、呼请扬升大师们，只要愿意呼请他们，他们就会帮助我们显化。如果大家希望自己的显化过程更快更轻鬆的话就可以呼请圣哲曼的临在，他会支持我们的显化。
** 第三步：行动
*** 如果不拿出具体的行动，什麽事情也不会发生。应该订定一个目标，朝那目标前进。
*** 具体行动不代表我们要拚死拚活的努力工作、做很辛苦的事情或勉强自己，而是顺应内在的指引；做自己该做的事情。具体行动是一个投入热情而且按部就班的行动，只要用正确方法来做的话，具体行动上可以非常轻鬆和顺利。
*** 如果目标比较大的话，好比买新房子，你可以先上网找房子。就算现在没有钱，就是要把能量场印刻在你想要的房子上面。只要你有办法得到那个体验，那个体验会印刻在DNA裡面，能量场就会整合这个体验，接著你就会陆续换房子，换到第二间、第三间，接著会把这个体验整合到内在能量场，接著就能陆续换房子换到自己理想的房子。
** 不断地重复三个步骤：抉择、祈请、行动。
*** 说要一个新房子。我得决定买一个新房子，然后上网找房子把房子模样刻印在脑海裡。然后拿出具体行动；找到新工作有更好的收入。接著就是祈请光明势力来帮助自己，接著问朋友有没有适合的房子，就这样不断地重複一直重複最后换到自己理想的房子。
** 实相塑造法
*** 有意识的专注在自己显化的事物上。专注包括看、想、听、触摸等。
*** 精确地专注可以精确地显化。
*** 可以专注在实物，也可以专注在模型。
*** 关注、感激并拓展生活中对自己有用的东西或东西有用的部分。
*** 专注在更好的人事物上面。
*** 听从内在的指引，走出舒适圈，花时间拓展眼界，才有更好的目标可以显化。
*** 克服恐惧，对干扰事物进行实相过滤法。
*** 使用实相塑造法，可以同时显化多个目标。
** 彩虹漩涡支持场
*** 我是临在会形成一个可以扩及整个地球的漩涡支持场。这个漩涡支持场可以吸引所有你要抉择要显化的人事物。
*** 在纸板上面描绘代表完美的人生的画面。可以画画把你要的完美人生画在上面，也可以把杂志上代表完美人生的照片剪下来贴上去。把觉得漂亮美好的图都剪下来，我们要用这个心灵地图和漩涡加持场加速显化你的完美人生。
*** 冥想、观想或者睁眼想象，身边有个水平的彩虹漩涡。彩虹漩涡将你心灵地图上面的人事物吸进你的生活；吸进你的身体。彩虹漩涡的旋转方向没关係，逆时针或者顺时针都可以，将心灵地图上面的人事物吸引到你的生活裡面。
** 实相过滤法
*** 显化逆转法就是一个抉择：不论在任何场合，你再也不会接受某一类人事物出现在你的人生中。
*** 强调“拒绝”，而不是专注在需要被否定的事物上。
*** 显化逆转法也需要点时间，对每一个错误的人事物说”不”和”拒绝”都是一小步的胜利。
*** 可以逆转过去显化的东西。先从小事情开始逆转，生活周遭的环境开始过滤我们想要发生的实相。
** 问答：
*** 感谢是有意识的了解现况知道现在的情形。要感谢宇宙中显化给我们的恩典和人事物，但不要感谢负面的人事物。
*** 如果不在矩阵裡生活不去贷款当奴隶不给自己更多经济压力，显化会更快一些。
*** 不是每个人会同意你的自由意志，你可以决定什麽对你比较重要。
*** 高维存有不会内在天人交战。他们很清楚自己要什麽，他们心智体、肉体、情绪体是统合的，所以可以马上显化他们想要的。
*** 你要对自己诚实，要很清楚自己到底要什麽，要丰田还是宾士。因为你的抉择会吸引到可以帮助你显化宾士的人事物。
*** 显化金钱：我该显化多少钱？钱怎麽来？好比说我想要银行有10亿。自己要想银行帐户或手上现金有多少钱。
*** 显化金钱并不是我是临在的本意。我是临在会帮助你显化金钱，让你想做的事情。钱只是工具，重要的是你要钱来做什麽，比如你想要新车，那麽买车的钱就会过来。
** 圣哲曼黄金漩涡
*** 在此共同呼请圣哲曼大师的临在。我们要将圣哲曼的黄金乙太能量漩涡锚定在这，等等观想黄金色乙太能量漩涡不断向外扩展，实现我们最崇高的使命，实现我们在场每个人的崇高使命。
*** 大家将贵金属摆在桌上以顺时针排列，走路的时候观想彩虹漩涡，吸引更多的丰盛，边走边观想吸引更多的丰盛，中间围成一个圆圈，绕著圣坛围著几个圈。
*** 现在观想圣坛出现一个彩虹漩涡。现在观想这个圣坛就是一个我们刚刚做的心灵地图。观想彩虹漩涡圣坛上的黄金和白银吸进地球的能量场；为全人类带来很多黄金白银，带来很多财富自由。
*** 观想彩虹漩涡让全地球人类带来丰盛，这是圣哲曼大师的伟大计划也是我们正在做的计划。
*** 现在桌子是我们的能量锚定点，可以为我们带来全部的丰盛。大家可以带回去早上带来的黄金白银当作是自己的钱母随身携带，它可以帮助加速我们的丰盛，这就是我们的钱母，一切如是如所祈愿，阿门。
*** 闭上眼观想彩虹漩涡帮助我们完成崇高的使命。等一下从外圈开始拿回自己的金币和银币，按照顺序拿回自己的金币和银币。
*** 继续回来排一个圆，现在大家手上拿著钱母，大家可以在未来使用钱母，可以让我们财富倍增，如果带银币未来可以带来很多银币。我们做钱母仪式很成功。
*** Jedi:我们在2014年7月Cobra教我们财富丰盛仪式，那时团队只有两个超光速粒子舱，现在已经有9个了，当时只有三个疗癒中心，现在有8个了。还有很多人在这个仪式过程中得到非常好的显化，生意变好或者财富变多了。
*** 本来是去上班后来自己做生意就非常成功的，本来我在那时财务上是很紧的，现在已经变得更加轻鬆可以完成更多的工作。谢谢圣哲曼大师。
*** 只要大家呼请圣哲曼大师，圣哲曼大师就会与你同在，现在帮圣哲曼大师的锚定，大家喜欢和金和银一起工作，它会为你和周遭亲朋好友带来丰盛。
** 丰盛冥想:
*** 将金黄闪耀的光吸进自己的身体
*** 将金黄闪耀的光发送到四面八方
*** 保持几分钟时间
*** 深呼吸将身体充满更多金黄闪耀的光
*** 这道金黄闪耀的光渗透到身体裡所有细胞，充满我们能量场
*** 观想自己化为一道金黄闪耀的光柱
*** 在此呼请圣哲曼大师的临在
*** 帮助大家显化个人、亲朋好友、以及好人的丰盛
*** 观想心轮发出金黄闪耀的漩涡、漩涡不断扩展
*** 观想金黄闪耀的漩涡吸引丰盛、吸引了黄金跟金钱还有房地产还有美好的车子还有最理想的人生
*** 观想一切美好的事物来到自己的人生
*** 花一段时间观想金黄闪耀的漩涡吸引一切美好的人事物
*** 观想圣哲曼大师放了一枚大金币在我们手上
*** 感受大金币的重量跟手感，感觉自己手指上的大金币，这是大家的钱母
*** 大家感觉一下手上的这一枚钱母
*** 从现在起可以把这个钱母放在口袋裡随身携带
*** 如果大家还没有钱母，那麽现在下定决心去买一枚金币/银币然后把这枚钱母放在口袋裡，这枚钱母从现在开始会替我们显化丰盛，圣哲曼大师会加持并且祝福你的决定，他会从现在开始帮助你显化丰盛。
*** 感觉所有的金光都停留在这个当下，感觉自己已经下定决心要买一枚钱母(金币/银币)。感觉手上的这一枚金币，现在慢慢的开始将意识带回自己身体。
