

* 显化法则资料如下：未整理
** COBRA:
** 所有实体世界显化出来的东西都是源自高维灵性世界的想法，我们一开始想要显化的东西都是一个想法和抉择，这个抉择会形成一个显化漩涡，然后这个显化漩涡会经过我们的光体门户来到实体世界。
** 如果大家知道这个原理，大家就可以用自己的专注来显化自己想要的事情，大家把注意力放在一个地方就可以打开一个门户进而显化自己想要的人事物。
** 如果想要显化一栋房子，可以买一个小模型屋放在自己的口袋里面，大家每天就可以从口袋拿出模型屋出来看，每天看，这个专注力就会开启门户让你显化出你自己想要的房子，大家真的不用担心，这是很有效的技巧，这个模型屋的样子就会和你理想中的房子是一样的。
** 如果大家不小心买错房子模型整天看的话那可能就会显化出不同的房子了，这显化技巧是非常具体精确的。所以买来的模型要尽量具体符合自己想要的。
** 我们可以做一个压缩突破模型放在每周实体聚会上面，大家聚会时就盯着模型看，大家都盯着模型看5~10分钟。
** 如果大家想要显化一个东西，最好的办法就是做一个缩小版的模型。如果大家想要太空旅行的话那么最好在家里买一个宇宙飞船玤的模型，这是一个非常具体的显化技巧。
** 现在我们已经做出了压缩突破的模型图片，大家可以使用这些图片去制作出压缩突破的实体模型，也可以做其它的显化用途上，这张压缩突破模型图片已经经过COBRA的确认，大家可以广为宣传使用。
** 
** 显化法则
** 柯博拉谈到显化过程以及罗斯柴尔德是如何以此获得权力并基本上控制了行星的。
** 我们必须对自己保持绝对诚实并在我们的生活中拥有足够的觉知去看我们是如何以及因何作出我们正在做出的那些选择的。否则的话我们的抉择会失真，我们的生活会偏离我们真正的目标。
** 一个相关例子是假设一个人想要获得来自其父亲的认可，因此选择了医学，接着成为医生这条道路。终于在晚些时候他意识到他想做一些完全不同的事情，一些他的心起初就真正想做的事情。
** 恐惧可以歪曲我们去看和选择我们真正想要显化的事物的力量。
** 就如上面那个例子反映的那样。这种恐惧只在缺乏对自己的诚实的情况下出现。
** 
** 显化法则有三个简单的步骤：
** （1）抉择
** （2）意志/呼请
** （3）行动。
** 每个思想和行动都会在无限的意识场域中创造出涟漪。我们比我们意识到的更加强大。
** 那些有着最强的与我是临在的连结的人知道这个真理。我们的我是临在正放射着我们信念的能量。
** 我们的思想以特定的频率过滤这股能量，接着这股能量滤过我们的情绪并最终显化为物质实相。
** 我们的信念可以改变世界。
** 我们正在这个星球上塑造着实相并且我们有强大的力量在协助我们——在天上以及地下。所以别害怕请求你真心想要的。圣哲曼说呼请然后你就会接收到。
** 来自于我是临在的抉择是更加强大有效的。我们必须如水晶般清晰并坚持我们想要的，不要摇摆不定。花点时间明确自己是值得的。
** 阴谋集团通过让我们认为知道自己想要什么并去追求它是自私的来误导我们。事件之后，显化会更加迅速地发生，在五维是即刻的。
** 呼请与意志涉及到使用我们的情感、想象和可视化来填充能量流，深入到我们想要的事物的细节。带着期待，但别沉迷于它，将其放下。然后无论如何，不放弃我们真心渴望的。
** 罗斯柴尔德知道这个并坚持了70年无论事情变得对他们来说有多困难。
** 行动就是根据你先前的抉择和呼请作出你被指引去做的行为，带着一种你渴望的已经显化的那股能量的体验去做，就像细胞语言一般。
** 
** 显化逆转法
** 我们可以显化，同样也可以反显化。只要简单地宣告“我不想要”我们生活中可能存在的许多我们不喜欢的事情，之所以存在就是因为我们没有作出对它们说不的决定。
** 我们有简单地直接离开某人或拒绝见他们的能力。我们可以在我们自己的环境-财产，家庭，关系等等中开始实践这一点，并将其扩展到整个行星层面。
** 144000人对阴谋集团说“不”将导致压缩突破。我们必须做出这个决定并保持专注。
** 
** 实相塑造
** 实相总是在持续地显化并在一个连贯的能量流中被创造出来。
** 如果我们认出在生活中起作用的部分并感激我们已经拥有的，我们就可以将这股显化之流扩展并创造我们想要的。注意这股能量的流动并拥有感激之心，我们显化的力量就会增强。
** 如果我们注意到事物的同步性，我们同样也能看出我们是如何与这股能量流连结在一起并经历实相的塑造的。
** 同样地，使用内在指引也会培养这个能力。愿意持续和坚持采取行动来朝向自己渴望的实相，以及脱离舒适区。
** 要有意愿通过物理的经验（不带评判地）周遭和内在增强的能量场域来扩展它.
** 同样地通过创造更高的目标和扩展我们的信念我们就可以扩展实相的球体。
** 接着柯博拉指导我们用一个非常物理的方式来协助我们自身的显化过程（之前他要求我们带杂志、大报纸、剪刀和胶水到课上）。我们分成小组，分享自己带的这些资源。
** 他要求我们将杂志中符合我们想要显化的事物的图片剪出来，接着当我们有了足够的图片，就把它们粘贴在每个大报纸上。
** 他给予我们足够的时间来做这个，这很有趣并协助我为整体进行考量的过程。
** 我发现和剪出的图片很接近我心中渴望的事物。当我将它们都粘连在一起时，这创造出一个有力的可视化。
** 之后柯博拉说我们可以观想我们的图片像一个在漩涡中旋转的朝向我们的能量场域。
** 我们可以对自己重复道“我的我是临在正在创造一个与行星交流的能量漩涡并吸引我想要的已创造和正在创造的情境到我的生活中。
** 显化 级别：专家

* 2017.3
** 
** 基本上每个人的我是临在都会发送能量波到我们生活的第三维度世界，我是临在连结最强的人就可以决定地球的实相。只要有一个人跟我是临在有完美的连结，只要一个人就能解放地球。我是临在祂会将祂的能量波发送到第七维度和七维以下所有的世界，这种能量波会经过很多层的过滤来到我们的现实世界。
** 
** 简单说一下。我是临在会发送自己的能量波，接著我们的心智层和情绪层会把我是临在的能量波转换成一种频率，接著往下降到情绪体，接著来自情绪体的能量再次沉降进来来到我们的现实生活。我们生活周遭就像是一层层能量过滤的结果。这就是我是临在显化实相的方法。现在说些细节。
** 
** 每个人是无极限的，人是无极限的。宇宙中并没有什麽是自然法则规范让我们不能显化的东西，你可以显化任何的东西。科学家都说这个不可能、那个不可能，他们说自由能源不可能，他们说光速应该是宇宙最快的速度。这是因为科学家的知识和眼界被阴谋集团打压，阴谋集团用负面科技打压人类的眼界，他们想塑造一个到处都有限制和控制的世界，阴谋集团他们本身就了解显化法则，这就是他们为何如此成功地控制这个世界，
** 
** 我会简单的说明向大家说明显化法则。身体有肉体、情绪体、心智体，有办法让肉体、心智体、情绪体统合到一致频率，我们就一定会成功。
** 
** 显化三部曲
** 
** 第一步是抉择、第二步是祈请、第三步是具体的行动
** 所有显化事物的法则就是依循三个步骤，我会很细节的跟大家说，做些实际的练习，所以第一步是抉择，人们很容易脑袋一团乱，有著各种愿望和想法及专案想要完成。
** 
** 有时会听从父母的抉择去做他们想要我们做的事情以及想要我们唸的学校，之后会发现都不是我们自己真正想要的。人心很容易因为各种期望和愿望而被迷惑，所以显化法则第一步要很清楚知道自己要的是什麽，如果完全不知道自己想要的是什麽，那麽显化出来的只是一团迷惑。
** 抉择第一步是要很清楚知道自己要什麽东西
** 
** 每天花5分钟去了解自己想要显化什麽，每天花5分钟就可以避免自己浪费人生。只要很清楚自己人生目标就能知道对于自己来说什麽才是最重要的。阴谋集团他们做的事情让我们内心天人交战，让我们不知道要做什麽，所以阴谋集团一直想让我们处于迷惘状态。
** 有时要让自己独处，让自己能够思考我这一生想要什麽。很多心智编程会阻止人们了解自己人生的真正目标。我说一些让大家了解一下。
** 
** 有些心智编程会影响显化能力。第一个是了解自己人生想要什麽是很自私的想法。如果为自己追求某种东西是很不灵性的行为，有很多洗脑教条都是这样跟你讲的。我会说:你的人生想法期望和启发是来自我是临在对你呼喊的缩影。
** 好比说现在有很强烈的指引告诉你想去南极洲，那可能是我是临在告诉你想去南极洲。这些想法背后是有原因的。如果了解显化法则的作法那就真的有办法去到南极洲，抉择就是关键。
** 抉择并不是只要5分钟就会变的东西，显化法则要成功，前提是抉择要一直不变，只要大家很清楚自己的抉择，基本上是不会变的，可能会有些变化，但重要的大方向是不会改变的，因为你真的很清楚你要什麽，你的抉择就是反应我是临在对你的诉求。
** 
** 很重要的是坚持再坚持绝对不要放弃，不管是遇到了什麽阻碍，不管别人怎麽说，永远永远不要放弃。
** 很多人会抱怨显化法则不成功是因为他们一下子就放弃了，他们可能距离成功就只有临门一脚，但却在成功前就放弃了。显化法则不光是要显化出金钱而是要显化出我是临在的神圣意志。金钱只是一个工具，而我们要用这个工具(金钱)在这世界显化出我是临在的神圣意志。
** 参宿七的黑暗势力在5,000年前引进了金钱奴役制度到地球上，但我们还是可以将金钱转换成神圣工具完成理想的崇高目标，我们仍然可以用金钱显化我是临在的神圣意志。
** 
** 圣哲曼在人间时他非常富有，他用金钱显化人类的自由，他非常精通显化法则。
** 你的抉择就反应出来自我是临在的意志，当你完全理解自己的时候。其实认识自我很简单并不複杂，我们不要自欺欺人不要骗自己，对自己完全的诚实，如果真的很讨厌一个人就让自己承认自己讨厌那个人，这样你才有办法转换这个恨意。如果不承认自己的想法，这些情绪就会一直堆积在那边。
** 有些人会做些错误的抉择隐藏一些事物，或者操弄某些事物或做些很奇怪的事情。有些人所做的抉择是为了得到父亲/母亲的认同，有些人并不想去唸医学院，他们只想为了得到父亲/母亲的认同而去唸了医学院，他们浪费了五年的时间学医，他可能会变成很厉害的医师，有著精湛的医术，但那个时候他就像行尸走肉一样每天工作8小时，当初只是为了完成父亲/母亲的期望。
** 他如果懂得显化法则，他其实可以告诉自己真正的想法来得到父亲的认同，那该怎麽做?其实他会发现只需要跟父亲花几个月时间沟通他就会认同我了，这样他就可以改行去做艺术家。
** 这是一个来自我是临在的正确抉择和其它错误愿望之间的差别，大家只要对自己诚实的话就会知道我再说什麽了。这个案例够清楚真实了。
** 有时对自己不诚实的人会很恐惧，恐惧只会在你对自己不诚实的时候变得强大，只要很了解自己是谁就不会恐惧。阴谋集团没有能力控制你，只要对自己诚实了解自己是谁，阴谋集团就不能威胁你也不能恐吓你，因为你的我是临在凌驾所有一切。所以只要你的意志够清楚强大，将是宇宙中最强大的力量。因为你的意志显化了我是临在的神圣意志，祂会自行显化。
** 罗斯柴尔德之所以可以过去那麽强大，是因为他们知道自己想要什麽，也有长远的计划。罗斯柴尔德家族的王朝始于250年前，当初的初衷很简单，他们想要统治这个世界，他们之所以这麽成功只有一个原因，他们永远不放弃一直坚持这个工作和目标，并且坚持了250年。
** 第一代罗斯柴尔德他也知道他没办活过250年看到这个计划实现，所以接著他们第一代将他愿望传承给儿子再传给孙子，他们花了70年就统治了美国，接著再花50~60年夺下俄罗斯，接著在花个几年就拿下全世界了。之所以这麽成功都是因为他们愿意花250年的时间准备和显化。
** 圣哲曼也很清楚自己要什麽所以花了350年时间实现，我也很清楚自己要做什麽所以花了20年的时间在做这些事情，所以大家也很清楚自己做些什麽，顶多花几年或者几个月就可以了。
** 因为我们一定会比罗斯柴尔德成功，我们跟我是临在的连结一定比罗斯柴尔德还要强，以全球观点来看我们一定比罗斯柴尔德还要成功，这是铁打的事实不会变的。
** 科学已经证实我们可以根据显化法则显化这个世界，唯一的事情是需要花些时间，因为全球有70多亿人的意识不太清楚所以需要花些时间，这就是为什麽地球解放要花这麽长的时间。
** 但我们的意志比较强健，因为我们的意志非常的坚定，所以看到很多的事情和真相，看到自由能源、看到新金融系统、看到阴谋集团的一切、看到传送门，拓展了大家的眼界。所以大家知道了大揭露也知道了事件，大家的愿望就是希望看到这些事情的发生，所以同时也要做好相对应的准备。
** 我知道这已经花了很久的时间，对我来说也真的花太长时间了，但我还是不会放弃要持续往前推进。
** 罗斯柴尔德和耶稣会有他们的弱点，他们还是会一直推进。另一方面圣哲曼也在实现自己的抉择，不管花200、300年他都不会放弃。有些人可能认为事件下礼拜发生，但他们准备好了吗?大家可以想像一下圣哲曼经历了第一次和第二次世界大战，在一个局势混乱的环境但仍然坚持下去。
** 大家想像正面秘密太空计划(SSP)的人看到太空船爆炸；而且登月也取消了，美国在这40年来都没有送人上太空。很多人在秘密太空计划工作40年还没看到完整的结果，有些人1975年就在秘密太空计划工作，而且在一般人所能达到的最高职位每天日夜辛劳，但还没看到成果。
** 但美国还是没办法把人送上太空轨道，现在2017年了，至今拖延了40年美国还是没把人送上太空，大家可以想像黑暗势力多想打压人类上太空。也有正派人士在幕后努力，过一阵子就能突破了。他们花了40年打基础，大家有没有办法打算再花40年为事件努力啊?(有!)
** 这时候意志就反应出我是临在的神圣意志。
** 第一步:你不会放弃，你很清楚了解自己的抉择就会反应出我是临在的神圣意志。
** 第二步:就是祈请，祈请的意思就是用情绪吸引帮助显化的各种人事物。
** 所以一旦有明确的意志就会和我是临在建立清楚的能量管道，接著就可以用情绪加速催化这股能量流，可以用观想或假装看到了要显化的目标了。也可以用情绪呼请光明势力帮助自己想显化的事物，可以呼请天使、可以呼请龙族、可以呼请抵抗运动，只要愿意呼请他们，他们就会帮忙。
** 关于第一步的抉择还要说些事情，关于抉择的事情刚刚忘了说了，抉择要尽可能的精确明确，抉择要很具体。有些人可能只想要新车，抉择要更具体一点，什麽样的具体呢?如果我要一台车，我会说:我要一台全新的捷豹跑车。车上要有GPS导航、涡轮增压还附加所有顶级配备。
** 有些人说:我想要第一次接触、我想跟星际兄弟姊妹见面。那麽我应该要具体一点。好比说:我要昴宿星人在我家的后院降落。他们会跟我见面；邀约我进入飞船畅谈10分钟。抉择越具体、目标越明确，就不会有些模糊不清的问题。
** 只要抓到各种精确细节就放到自己情绪和观想画面裡，不过有时会有些变化，有些细节好比那台捷豹可能是从金属色或变白色，这只是小细节还好。如果真的完全精通显化法则，可以显化到每个目标的细节。精准的程度会让人吓一下。惊叹:这根本就是我想要的东西。
** 有了明确的画面就可以关注在那个画面，但不要变成迷恋和痴迷了。一旦很清楚显化法则，目标一定会实现。但人生一样要往前迈进，不是说要说服自己，祈请是显化法则的一部份，所以就一直的观想成天在观想，不是说这是显化法则的一部份就踟蹰不前。只要很清楚是显化的一部份，显化法则就一定会成功。把抉择愿望先放心裡然后过好每一天，
** 第三步:就是具体的行动。如果不拿出具体的行动，那麽什麽事情也不会发生。你可以下定一千个抉择每天祈请，但不拿出具体行动什麽也不会发生。大家应该做的是订定一个目标，朝那目标前进。
** 好几千个网友每天看我部落格说事件还没发生，但他们什麽也没做。每天都在等金融重置，然后说他们在金融重置之后要盖一千台超光速粒子舱。如果只是些空谈没有具体行动这样什麽也不会发生。
** 虽然金融重置还没发生，但这也是我们显化的目标之一。如果只是痴心妄想什麽都不做那就什麽也不会发生。具体行动不是说要做很辛苦的事情或勉强自己，而是顺应内在的指引；做自己该做的事情。就像是顺著指引去南极洲。所以如果要去南极洲，我应该要订机票然后打包行李或找人帮你打包行李，不一定要自己很费力的打包行李。
** 如果目标比较大的话，好比买新房子，你可以先上网找房子。就算现在没有钱，就是要把能量场印刻在你想要的房子上面。只要你有办法得到那个体验，那个体验会印刻在DNA裡面，能量场就会整合这个体验，接著你就会陆续换房子，换到第二间、第三间，接著会把这个体验整合到内在能量场，接著就能陆续换房子换到自己理想的房子。
** 好比说大家想要第一次接触。大家可以先去51区了解当时的场景，或可能需要去罗斯威尔待上几天。可能光看书还不够，需要现场更实际的体验。亲身体验就一个具体行动的案例。真的不需要害怕，一定要去做。
** 很多人来自世界各地，从世界各地来到台北参加这场会议。来到这裡就是一种具体的行动，每个人都不辞辛劳来到这裡，回过头来看好像也没多难，也不是多艰钜的挑战，每个人都来到了会议现场，恭喜大家。
** 显化法则关键就是不断的重複三个步骤:抉择、祈请、行动。
** 接著好比说要一个新房子。我得决定买一个新房子，然后上网找房子把房子模样刻印在脑海裡。然后拿出具体行动；找到新工作有更好的收入。接著就是祈请光明势力来帮助自己，接著问朋友有没有适合的房子，就这样不断地重複一直重複最后换到自己理想的房子。
** 显化法则为什麽失败?是因为太早放弃了所以失败，显化法则没办法马上实现是因为我们住在稠密的实相，所以需要时间显化。如果显化一个午餐可能要花5~10分钟，如果做一个可以用的自由能源机器可能要花5~10年，如果在三年研发期间都放弃了那就不会做出自由能源机器。如果要显化新房子，常理来看可能要花10~20年。
** 就算懂得显化法则想要一个房子也要3、5年的时间，如果第三年就放弃了那麽一切都白费了，如果你看过很多房子但没去买，那就白做了。
** 开放提问:
** 与会者：我自己用显化法则想要同时显化六个东西会不会有影响，显化力量会不会变弱?
** COBRA：你要同时显化多少都可以，没有影响。我个人目前在显化四百个专案。
** 与会者：如果说我想要的东西有符合我的灵魂内在指引会不会比较快呢?
** COBRA：是的，会比较快一点。
** 与会者：我想请问高维世界存有为什麽能马上显化东西?
** COBRA：高维存有不会内在天人交战。他们很清楚自己要什麽，他们心智体、肉体、情绪体是统合的，所以可以马上显化他们想要的。
** 与会者：我是一个两个小孩的妈，我的显化可以包含我两个小孩吗?
** COBRA：我讲的显化技巧都是为你个人使用的。你有你的自由意志，不管你小孩几岁也拥有自由意志。有时父母也会忘记自己小孩有自由意志，养育小孩是一回事，但要强加自由意志在别人身上是另一回事。自己的目标可以包括让自己的小孩可以有幸福快乐的生活，但不要显化我小孩明天要穿这个衣服、明天去学什麽。如果小孩喜欢听重金属音乐那就让他听吧，就算他不喜欢听巴哈古典音乐那也没有关係的。
** 与会者：假设小我说我要买丰田汽车，但是高我却希望给我宾士。请问小我的抉择对高我来说是不是一种限制?
** COBRA：我来解释一下。如果真的很明确了解自己要什麽，不管自己有多少钱一定要这台车，因为你的抉择会吸引到可以帮助你显化宾士的人事物，并不是每个人都要路上开著双B。有些人就是喜欢开丰田的车。你要对自己诚实要很清楚自己要什麽，自己要丰田还是宾士，要知道自己到底想要什麽。
** 要稍微想一下可能要改变自己做事方法和自己看待价值观的方式。
** 与会者：如果我真的想要显化金钱，该怎麽做?
** COBRA：这个抉择太模糊。我应该要想:我该显化多少钱?钱怎麽来?好比说我想要银行有10亿。自己要想银行帐户或手上现金有多少钱，一旦有清楚的抉择就可以开始显化。
** 显化金钱并不是属于我是临在的本意。我是临在会帮助你显化金钱，让你想做的事情。如果今天钱没有购买力，那它只是一张普通的纸而已。钱只是一个代表性的交易工具。重要的是你想要新车子、新房子或更好的人生。
** 如果目的是要钱和房子车子及更好的人生，那钱就会被吸引过来，所以比较重要还是你要钱来做什麽。好比你要一台新车，那麽买车的钱就会过来了。
** 与会者：假设两群人精通显化法则，但双方显化方向完全相反，那会发生什麽事情?
** COBRA：这是目前现在的状态，也就是光明势力和黑暗势力非常精通显化法则。大家想像地球上有两家公司。一家是罗斯柴尔德公司，另一家为圣哲曼公司。
** 塑造实相
** 现在来说些进阶知识。银河联盟会利用实相塑造技术来塑造想要的实相。我向大家解释这些，大家可以带回家使用。所有实相都是透过门户来显化的，我们现在所看到所有事物都是透过电浆门户显化到我们日常生活中。其实每个原子都是一个星门，都是一个挠场形状的星门。
** 大家知道这就是女神漩涡
** 我们要利用女神漩涡的能量显化我们的事物。现在来解释一下，每一次的显化都是灵性和物质互动的结果。昨天有讲到我是临在就是上面的灵性，我们的精神情绪和抉择都透过这个往下到达这个转捩化点门户显化在我们现实生活。刚刚提到显化法则三大步骤最上面是抉择，再来是祈请及具体行动，然后到了转捩点的时候显化就会发生了。
** 只要一直按照这三个步骤总有一天就会显化成功。好比说为了一个房子已经显化了五年，有一天突然开车看到一个房子就这样买了。现在显化一个目标到你生活的时候，其实有个方法可以大幅加速大家显化过程，这个叫实相塑造法。
** 实相并不是一个死板板的固体而是内在意志的反射，所以可以利用实相塑造法来塑造我们的实相，用专注的意念塑造实相。
** 好比我关注这个如意宝珠，突然有一天几百颗如意宝珠跑到我的生活裡面。如果想用实相塑造法就要有意识的专注在自己显化的事物上，大家都知道自己生活的属性，每个人生活属性都不太一样，每个人显化的人生目标有不同抉择，有些人可能在显化的过程，也有人已经显化了。
** 生活中一些实相有助于我们显化也有些实相没有帮助，好比我的身体健康状况是OK的但其它方面可能不太好，好比用气场照相机帮大家拍气场照片，就能看到大家生活有什麽状况。
** 如果要显化一个实相永远来自于一个当下，永远关注生活中对自己有用的东西。好比我今天想显化一台捷豹超跑，但我现在开的是丰田，然后觉得我必须开更好的车想甩掉旧车。但如果一直坚持开著旧车，那麽你可能就会越开越差的车，永远开不到捷豹超跑。
** 大家可以这样说:虽然我现在开的是丰田，不过我值得开更好的车。我能开到捷豹超跑，接著显化就会朝这个方向演进。所以下一步就可能升级成奥迪或BMW，虽然还没到达捷豹的目标但已经往那个目标迈进了。人生迈进一步就可以更上一层楼了。
** 假设现在有个人说:我口袋装的如意宝珠好小颗。这时候你的意念应该要说这颗如意宝珠虽然小但是价值远高于鑽石而且更珍贵。这样子你就真的可以显化出换到更好的。所以专注自己的意念，专注在更好的人事物上面，你专注的方向就像一个能量漩涡接著就会显化。
** 我再说一次。如果我的想法认为:我这台丰田又旧又破，我想要甩掉这台车。可能就会有人想买走你的车。如果我的想法是我有台可以用的丰田，但是我还可以开到更好的车，结果就会是可以开到一台更好的新车。
** 实相塑造法的基本观念是____专注自己意念；用意识去拓展有用的部份____。好比说现在有一间公寓，那麽可以感谢这间公寓，这样一定会有更好的结果出现，接著就升级成一栋房子了。
** 实相塑造法像是一个正面思考。他不是单纯发好愿，而是有意识的让自己的生活步步高升往上爬，就像已经很了解生活周遭处境，所以朝更好的目标前进，把好的变成更好的。
** 好比说不光是显化的物体而是一个处境或者情境，不管是物体或情境，我是临在的力量都可以进入这个情境来改善。
** 开放提问:
** 与会者：我们要如何用这个方法显化事件?
** COBRA：用这个方法显化事件时，要说感谢已经发生的事情，用这些基础往事件迈进。好比说大揭露还没发生，我们感谢现在已经有的努力，感谢已经发生的委婉揭露，让我们朝大揭露迈进。
** 现在网路上出现了部份小揭露的文章，虽然不是阴谋集团全部被逮捕但已经有些被逮捕了，虽然新金融系统还没上线但我们朝这个方向迈进了，上海黄金交易所是一个例子，中国有自己的交易平台。只要知道这些进展就可以有意识朝更好的方向发展。
** 与会者：有关于佈施福报和显化法则的关係，我们常说要有佈施，才能够有福报让自己生活更好?
** COBRA：如果是把自己能量投注在地球解放事物上对自己也会有帮助的。如果正确的佈施就会把自己能量流分在有意义的地方上面。
** 与会者：感恩是不是实相塑造法的一部份?
** COBRA：感谢是有意识的了解现况知道现在的情形，但不是像新时代运动一样感谢负面的人事物。我们要感谢宇宙中显化给我们的恩典和人事物，但请不要感谢负面的人事物。
** 与会者：假设事件后有物质产生舱要显化什麽物质都有，我们是不是还要感谢，用实相塑造法来显化自己想要的东西?
** COBRA：物质产生舱和塑造法原理很像的，可以透过一步一步进阶。
** 与会者：我是临在是在哪个维度时空?
** COBRA：我是临在无所不在，我是临在是超越所有维度的存在并不侷限在特定维度，我是临在和神圣本源是连接的。
** 与会者：刚刚提到统合能量场加速显化，那探测术是不是也可以加速显化?
** COBRA：没有。现在说的是自然法则而不是一种操纵能量的技术。
** 与会者：我知道很多人都在想办法显化金融重置，那为什麽都还没发生?
** COBRA：很多人在显化重置但都是在做白日梦，都在痴心幻想完全没有具体的行动。有些是基于错误抉择错误决定才想让重置发生，好比说有些人是想去买伊拉克第纳尔、辛巴威币想趁金融重置后套利赚大钱。
** 新金融系统不光是调整货币汇率，新金融系统是要全新打造全新的系统，很多人想要金融重置的都在做白日梦，就算有具体行动正在进行金融重置的人也需要花些时间，罗斯柴尔德花了250年打造现在的金融系统，我们想花10年左右做新金融系统，我们不需要花250年，我们过去花了10年，现在再花些时间就能看到成果了。
** 与会者：我们认为成功必须经过努力和受苦这个信念对显化是否有牴触或者不正确的?
** COBRA：受苦或牺牲才得到成功的概念是执政官创造的编程，他们就是要製造更多的苦难，所以他们就创造一个信仰系统说受苦受难是一种美德，显化和受苦受折磨一点关係都没有，那些事情没有任何崇高的目的。
** 拜託不要再说地球是学校了，也不要花钱当卡奴。如果地球真是所学校，那麽有谁会想来这裡唸??
** 与会者：我可不可以透过设定心智让我自己随时和我是临在合一而不透过冥想?
** COBRA：最好不要靠设定，用简单的冥想和我是临在连结。
** 与会者：关于中国金融系统。如果不在矩阵裡生活不去贷款当奴隶不给自己更多经济压力，显化是否会更快一些，如果不去因为买房子而贷款去做更多有助于光的事情。
** COBRA：是的，非常好。
** 
** 现在讲显化，等等详细说明显化逆转。等等详细和大家说明。
** 再来解释一个重要的事情，如果用这个实相塑造法，我是临在的能量就可以源源不绝的流进我们能量场，就可以一直使用显化能量流。好比说这时可以同时显化好几个目标好几个抉择。有些抉择非常重大，好比显化事件发生这就是重大的。
** 宏远的目标:好比我要解放整个宇宙。比较中层的目标:比如买新房子和有更好的生活，如果是小目标:我要一个CD，很快就能在网路上马上找到这个CD。
** 用实相塑造法会有持续显化能量流进入能量场
** 上面是我是临在，下面是心智体、情绪体、肉体。下面是将能量显化到现实生活。如果可以一直持续使用实相塑造法就可以拓展眼界看到正面的人事物和东西，只要跟我是临在连结就可以获得我是临在的指引，收到的指引并不一定是最终显化的目标，我是临在给你的指引都是下一步的目标而不是告诉你完整的目标。等等会说个案例。
** 好比我要设定一个目标。就好比我今天要在夜间爬山攻顶。我现在的周围是一片黑，手上只拿著手电筒照亮前面的路。我们仅需要知道路前面两三步是不是安全的就可以了，只要用这个方法就可以在夜间完成攻顶。这就是内在指引的给我们提示的作法。
** 如果听从内在指引就会告诉你下一步走到哪裡去。很多人都不想听从指引，因为有时候内在指引会让你走出舒适圈。好比说现在要去南极洲，内在指引会说去户外用品店买件抗低温的服装。那时候你也许会出现觉得这衣服好贵之类的想法。
** 如果不听从内在指引，你的内在指引就会越来越弱。如果听从指引内在心声就会越来越强。因为呼应内在指引，我是临在就会给你更好的指引。只要顺从内在的指引和实相塑造法，基本上可以显化所有的事物。我透过这样的技巧显化了8、9成的抉择了，我自己亲身经历了这些，这是有用的。
** 我知道那种长远目标花比较多时间，但这套技巧是有用的，有时候会阻挡你扩展眼界的东西是恐惧。刚刚有人问关于金钱的问题，我要顺便讲关于眼界圈的事情。
** 每个人生活都是由眼界圈来决定的。有些人会有自我设限的想法，认为人生只要有车子有稳定工作就好了，这种眼界圈来自生活的经验和价值观。很多人的眼界圈不包括到外星球旅行，通常都是过很简约的生活。很多人认为年收入10万美元就很好，但是手上握有一百万美元现金超过他们眼界了。
** 想显化更好的东西就必须拓展眼界，而我们可以亲身体验一下你想体验的东西。好比说真的想飞上太空和月球就去参加太空营队，接著想登月就去参加太空营队实际观看太空船模型，这时能量就会印刻在我们身体裡面。
** 如果接收高我的崇高目标并且呼应那个指引，你的眼界就会提升，好比说一个人眼界一开始年收10万美元就很厉害了，接著高我会给你一个经验和体验扩展你的眼界。高我给你一个机会让你体验开顶级超跑一个礼拜，接著可能会参加一个派对遇到让你大开眼界的贵人。这时你的眼界圈和价值观就被拓展了，因为你在体验一些事情之后就会发现很多事情都是有可能的。
** 如果你想要登月，那麽你的眼界圈可能要拓展到跟伊隆·马斯克见面，接著可以开始显化你登月的费用:17,000,000万美元。我说的是一个大概的理论，每个人都能做到你们想要做到的事情，说不定两百个人明年就能一起登月了，这有什麽不可以。
** 拓展眼界相信这是可能的，你也做得到。即使我们花个3年时间去完成，这在自然法则也没说这件事情行不通。我知道很多台湾人资产都超过1,700万美元。这些大金主们何尝不资助我们团队呢?反正他们没理由不资助我们。拓展眼界可以把任何事情变得可能。
** 花时间开展眼界让自己相信这是可能的，事件发生的那一刻就是让人类集体眼界扩大，让大家认为说这是可能的。
** 现在开放提问:
** 与会者：我最近透过显化法则显化出我的目标，但这个目标引起家人不谅解，该怎麽办?
** COBRA：我忘了解释这个。我要说你的自由意志就是你的自由意志。不是每个人会同意你的自由意志，你可以决定什麽对你比较重要，很多人不认同我在做的事情，但我来自我是临在崇高目标对我来说比较重要。你的家人不认同你显化的东西但那就是你真正想要的。如果你家人真的爱你，那麽总有一天他会谅解你。如果他们不爱你，他们就根本不会在乎。你的人生自己好好过。
** 与会者：直觉算不算是一种内在指引?
** COBRA：是。不一定全部是。真正的直觉就是。
** 与会者：罗斯柴尔德他们跟我是临在连结应该很弱怎麽还可以显化这麽多东西?
** COBRA：答案会让你吓一跳，罗斯柴尔德跟他们我是临在的连结也很强。他们是非常进化的一群人，他们跟内在有非常强的连结但他们的意识被植入物扭曲的非常严重。他们对世界的认知变得非常扭曲。罗斯柴尔德家族能使用内在指引，但会使用在做坏的事情，有些人精神力非常强，但却会用自由意志做些坏事，这种问题在地球上特别严重，因为主要异常就聚集在地球。
** 罗斯柴尔德非常了解显化法则，问题是他们误用这些知识。我们自由意志比较强而且我们方向是正确的，这就是为什麽我们不需要再花250年显化一个新的金融系统。
** 与会者：去医院做志工算不算是一种内在指引?
** COBRA：当志工得到启发那对你是好的，如果去那当志工获得启发就是自己的内在指引，那就是好的。
** 
** 显化过滤法
** 今天早上会议剩下最后一部份，现在来说实相过滤法。简单来说如何不要在显化生活中不想再度发生的人事物。刚刚教大家如何显化想要的东西，那世界上也有你不想发生的事情，现在要来讲怎麽做。
** 我们刚刚讲到实相圈。这就是实相圈也可以说是眼界圈。在这个眼界圈裡面你决定什麽事情应该发生，哪些事情不该发生，透过抉择来决定这些。
** 能够连结我是临在时让这两件事情同时发生。可以选择不发生或发生。跟我是临在完美连结之前这两件事情也会发生但不是完美的，人生中有很多我们不想发生的人事物。过滤法原理很简单，就是下一个抉择。举例说:我决定这件事情停止出现在我的生活。显化逆转法则让这些事情停止出现在我的生活。
** 如果我的生活反覆出现同样的困境，那并不是一个课程。你唯一需要学会的是下定决心对这些困境说不、立刻停止。我以前会遇到跟别人开会，别人一直迟到。我就一直等。有一天，我决定说:从现在开始，我只等15分钟。如果对方没出现我就要走了。这个方法，让我15年来不但不用等别人，反倒是别人还要等我。
** 因为我不喜欢每次开会都要等人1、2小时，还要问对方会不会到。突然有一天我想我有办法改变这个实相，之后我就下定决心，下一个抉择说我只等15分钟，再久就要走了。这个方法适用生活中各种状况。如果是家暴受害者，那就对家暴说不，这些事情就不会发生在他们身上。
** 如果众人的决心够强大，决心对阴谋集团说”不”，他们就会被逮捕。根据显化法则:如果人类集体对阴谋集团说”不”，他们就会被移除。
** 我们用显化过滤法来过滤我们想要的实相，用同样的显化技巧来把不想要的实相排除在我们生活以外。阴谋集团之所以可以控制人类长久时间，就是因为人们对阴谋集团说:你们可以进入我的生活。所以人们相信必须守法、必须服从、过著受苦受难的日子。
** 有些人认为受苦受难有助于灵性成长，认为政府有权收税，也有些人认为世道就是如此，逆来顺受，将就就好。事实上我们有权说”不”。对不喜欢的事情说”不”这就是我们过滤实相的方法。
** 显化逆转法跟显化法则一样:拒绝实相发生也需要点时间，我们生活当中很多面向被控制。我们要下很多抉择，对这些实相说不。我们必须对植入物说不，必须对化学凝结尾说不，对有毒的食物说不，对主流媒体说不，我们要拒绝的东西太多了，对每一个错误的人事物说”不”和”拒绝”都是一小步的胜利。
** 所有累积至今的问题都是过去人们觉得可以有网路审查、可以接受有毒食物、可以有政治监狱，让各种不合理的事情把它认为是合理的。现在终于许多人受够了，这就是一个觉醒的过程，觉醒不是虚无飘渺的说词，也包括我们对于生活现况困境受够了，对不想发生的事情说”不”，拒绝这些不想发生的事情，虽然可能说10次”不”裡会有一次的妥协。对于人类处境拒绝10次，可能会不小心妥协一次。
** 我们不光是显化我们要的，也可以逆转过去显化的东西，可以先从小事情开始逆转，生活周遭的环境开始过滤我们想要发生的实相，好比从生活居家住宅开始。
** 我们可以开始打扫自己的家裡，把不再需要的东西都清除。把家裡用不到的东西都丢掉，因为那些东西会阻碍能量的流动。大家也可以断绝没有用的人际关係，他们会耗尽你的能量。
** 开始培养对你有帮助的人际关係。你根本不需要有一千个不会关心你的脸书好友。说不定你也根本不需要有社交软体，也不需要看电视，也可能不用每天滑手机上部落格然后发讯息。
** 执政官会让人们一直沉迷于手机，一直分心。懂得过滤实相后，人生就可以往上进阶，开始逆转这些有毒的食物，接著可以用全球规模逆转阴谋集团造成的负面结果。
** 一旦我们人类在集体意识上说”不”，对他们说”不”达到临界质量，阴谋集团就不会存在，一旦有144,000人说”不”，阴谋集团就结束了。一旦有144,000人说”不”，地球上就会发生一个情境使得阴谋集团不适合在这生存。那个时候就是压缩突破。
** 我们在2月26日的乙太层解放冥想达成了一半的”不”，我们在冥想后30分内维持抗拒阴谋集团的能量场看到了成果，事件后这种能量场将会永远存在，我们将会用集体意识的力量对阴谋集团说”不”。
** 开放提问:
** 与会者：显化事件的人和不相信事件的人在事件之后会有不同的实相，这是不是真的?
** COBRA：不会。事件是每个人都会经历和面对的事情，不管你相不相信。
** 与会者：抵抗运动为什麽要叫抵抗运动?
** COBRA：抵抗运动这个团体的名称在压缩突破发生之前都还算是合适的，抵抗运动在压缩突破完成之后就会融入银河联盟。目前抵抗运动的功能就是加速事件，因为他们在负责抵抗阴谋集团的活动我们才能活到现在，也包括我，要不然我今天也不会坐在这裡了。
** 与会者：如何使用转化的门户在自己的显化逆转法?
** COBRA：刚刚讲到转化点是个门户，让显化的东西逆转，一个东西就不再显化了。人要观注想显化的实相而不是看想要的。一个坚定的抉择可以让这件事情不会发生了。下定决心决定你想要什麽，哪个事情不要发生。像是下定决心不要再等迟到的人，我不会关注对方迟到的实相，而是关注自己的部份，所以我只等15分钟就离开了。
** 今天下午有很多事情要做，会非常的紧凑。
** 大家都到了吗，今天来到第二阶段，今天要专注于创造新的世界，今天早上讲了如何使用显化法则，现在就要用这样的知识来显化新的世界。
** 现在开放问答时间
** 与会者：地球从第三维度转到第五维度的部份，这个人的频率比较高的话有没有可能在三维实相中存在于第五维度的状态，像是扬升生活中?
** COBRA：当你有办法达到第五维度意识后就不需要生活在三维世界裡，那时你的身体就不再只是身体而是个投影，但仍然会有个肉体，不过那是第五维度意识的投射。
** 与会者：我们华人的EVENT中文翻译裡直接翻译叫做事件，华人99%描述黑暗事物，这个对于让我们分享事件的动作不太方便，社会大众听到会关闭他的心门，建议能够选一个更好听的中文名字，能方便分享，让普罗大众散佈这个好消息出去，是否支持这个改变?
** COBRA：我不懂中文我没辙，不好意思。
** 与会者：光明势力有没有新的进展关于香港的，之前的都属于全世界很久没听过香港，之前听过香港说正面势力黄金这边之后就没有了。
** COBRA：几个礼拜之后会公开。
** 与会者：Cobra曾说过台湾是转变的中心，我们承办六次会议，为什麽当初会选择来到台湾，台湾有什麽特别原因让我们投生在这裡?
** COBRA：过去有一个很强大的灵魂团体一起旅行。这个灵魂团体和正面龙族有很强的连结。他们当时决定在这一世投生在台湾。
** 
** 漩涡支持场(地图)-特殊显化技术
** 
** 我们要讲光体的能量场，(图)这是我们的能量场，会用我是临在有意识的创造出我们想要的实相。我是临在会创造出一个漩涡场，这个漩涡能量场，可以吸引你希望显化的人事物。
** 我们要来具体练习一次教大家如何使用这个漩涡支持场。基本上大家的我是临在会形成一个漩涡支持场，可以说我是临在形成一个漩涡能量场是电浆型态的能量场也是高维世界的能量场，这可以扩及整个地球。这个漩涡支持场可以吸引所有你要抉择要显化的人事物。
** 今天要来学习如何使用这个漩涡支持场。现在说些实际案例，我在很久以前想要卖些房地产，我不想用一般管道就用冥想开启漩涡支持场，我就在冥想中设定意念，我观想第一个买我房子的人今天第一天来到我家买下我的房产，然后隔天就接到电话说要买我的房产然后就买了，这就是冥想技巧的强大。
** 现在教大家如何使用这个漩涡支持场，现在我们更进一步使用漩涡支持场，用这个技巧帮大家显化完美的人生，大家可以开始设计完美的人生去显化完美的人生。
** 待会20~30个人分一组。我们要开始创造属于我们的人生，我们要来使用心灵地图练习显化法则。
** 请大家在纸板上面描绘代表完美的人生的画面。可以画画把你要的完美人生画在上面，也可以把杂志上代表完美人生的照片剪下来贴上去。把觉得漂亮美好的图都剪下来，我们要用这个心灵地图和漩涡加持场加速显化你的完美人生。
** 现在已经做好一张代表我们完美人生的心灵地图，如果还没有做好的人休息时间可以继续做。休息时间过后这边要清空，稍后大家要一起来做个仪式。
** 休息时间前做一件事情。现在做个简单的冥想，观想身边有个水平的彩虹漩涡(图)；彩虹漩涡将你心灵地图上面的人事物吸进你的生活；吸进你的身体。彩虹漩涡的旋转方向没关係，逆时针或者顺时针都可以，将心灵地图上面的人事物吸引到你的生活裡面。
** 
** 
** 彩虹漩涡示意图(上下直立)
** 大家可以张开眼睛想像彩虹漩涡，将心灵地图上面的人事物吸引进你的生活，这个就是你用来加速显化过程的模板。20年前我做了人生第一张心灵地图，大概在10年前我做了另一张地图，第一张地图有8、9成已经实现了，所以用了第二张地图，第二张也有8成实现了。大家可以用心灵地图当作是自己显化的模板，大家可以使用彩虹漩涡加持场改变你的生活，不管什麽都可以。
** 大家也可以在实体聚会一起冥想，一起使用彩虹漩涡吸引大家想要的人事物，当大家实体聚会时可以一起用彩虹漩涡吸引大家共同想要的人事物，集体显化力量比个人显化力量还要大很多。
** 现在开放相关问答:
** 与会者：如意宝珠能加速显化的原理是什麽?
** COBRA：如意宝珠用途并不完全是加速显化，而是可以传导事件的压缩突破能量。如意宝珠之所以可以加速显化，是因为它强化了配戴者与自身我是临在的连结，因而可以更容易显化你要的东西。
** 与会者：分享对于昴宿星创造者的概念?
** COBRA：他们心目中的创造者就是合一，就是神圣本源”绝对”。
** 圣哲曼黄金漩涡
** 现在要做一件事情。
** 在此共同呼请圣哲曼大师的临在。我们要将圣哲曼的黄金乙太能量漩涡锚定在这，等等观想黄金色乙太能量漩涡不断向外扩展，实现我们最崇高的使命，实现我们在场每个人的崇高使命。
** 大家将贵金属摆在桌上以顺时针排列，走路的时候观想彩虹漩涡，吸引更多的丰盛，边走边观想吸引更多的丰盛，中间围成一个圆圈，绕著圣坛围著几个圈。
** 现在观想圣坛出现一个彩虹漩涡。现在观想这个圣坛就是一个我们刚刚做的心灵地图。观想彩虹漩涡圣坛上的黄金和白银吸进地球的能量场；为全人类带来很多黄金白银，带来很多财富自由。
** 观想彩虹漩涡让全地球人类带来丰盛，这是圣哲曼大师的伟大计划也是我们正在做的计划。
** 现在桌子是我们的能量锚定点，可以为我们带来全部的丰盛。大家可以带回去早上带来的黄金白银当作是自己的钱母随身携带，它可以帮助加速我们的丰盛，这就是我们的钱母，一切如是如所祈愿，阿门。
** 闭上眼观想彩虹漩涡帮助我们完成崇高的使命。等一下从外圈开始拿回自己的金币和银币，按照顺序拿回自己的金币和银币。
** 继续回来排一个圆，现在大家手上拿著钱母，大家可以在未来使用钱母，可以让我们财富倍增，如果带银币未来可以带来很多银币。我们做钱母仪式很成功。
** Jedi:我们在2014年7月Cobra教我们财富丰盛仪式，那时团队只有两个超光速粒子舱，现在已经有9个了，当时只有三个疗癒中心，现在有8个了。还有很多人在这个仪式过程中得到非常好的显化，生意变好或者财富变多了。
** 本来是去上班后来自己做生意就非常成功的，本来我在那时财务上是很紧的，现在已经变得更加轻鬆可以完成更多的工作。谢谢圣哲曼大师。
** 只要大家呼请圣哲曼大师，圣哲曼大师就会与你同在，现在帮圣哲曼大师的锚定，大家喜欢和金和银一起工作，它会为你和周遭亲朋好友带来丰盛。
** 休息时间。
** 创立光之社区
** 我们要进一步的显化新世界，我们不要等待事件，我们要亲自显化事件。过去讲过几次光的社区，去年七月讲过光之社区。大家大概知道了一点概念。圣哲曼大师指示我，不要等待事件，我们要现在开始创建光之社区，现在我们要打造地球上第一个光之社区。
** 在几年前有一些龙族已经选定好光之社区的场地，现在请Alex解释现况。我稍后会补充。
** A：好久不见。地球上有些一般民间人士可以使用的龙门门户。这些门户分佈在地球上某些角落。龙门是通往地下阿加森世界的门户，龙门不受政府或其它单位的掌控，现在我们发现了一座龙门，一个和我们合作的团体买下这个区域，买下的土地和龙门还满接近的几乎都在上方，跟我们龙族合作的团体买下很多龙门和龙门周遭的土地。
** 生活在这些土地周遭的村民流传一项传说:说这些土地上会有龙在盘旋，现在已经有这样的土地可以开展地球上第一座光之社区。
** 光之社区形成的条件需要一块土地，底下是亚特兰提斯的旧赤道，有一块土地在泰国。
** COBRA：有内在指引想住在光之社区的话可以用mail联络我，台湾地区的话联络请找Jedi，大家就可以收到进一步的指示。
** 光之社区的基本原理是要用神圣几何来建造建筑物。一位建商会用神圣几何盖房子，他的房子造价比外面便宜很多，结构都是半圆形类似巨蛋一样，他们尺度都是按照神圣几何打造的。
** 基本概念就是说感受到内在指引就买下这间半巨蛋型的房子，然后开始住在裡面，这是兴建光之社区的第一阶段。虽然执政官还没被移除，阴谋集团也还没垮台，但我们不能再等待了。现在就开始创造光之社区，有兴趣的话可以连络我或Jedi，我会给参与者进一步的指示。加入计划的人我会加以审查。当然，现场的各位已经准备好可以加入这个光之社区了，对这个计划有兴趣的人可以连络我和Jedi。
** 这个社区并非蛮荒部落，社区中有网路、有水、有电，基本上就是一个基础设施很完善的社区，会请建商预铸好建筑的结构，然后到现场组装。
** 这个社区裡面有个重要的关键，那就是社区裡面人与人之间的人际关係。执政官倾向创造人与人之间的衝突，虽然我们越来越接近压缩突破，但住在这个社区的人一定要学会守望相助互相合作，虽然是自己买一栋房子住在这裡，但还是得互相合作彼此融洽生活。
** 住在光之社区目的就是要锚定圣光，显化圣光。这应该会是第一次公开接触之前会有飞船降落的地方，我们要创造光之社区跟(图片)景象很接近。
** 与会者：请问光之社区的居民还需要用钱吗?
** COBRA：目前光之社区还是要用到钱，还是得用钱买食物和所需要的服务。
** 与会者：请问光之社区跟乌本图、维纳斯计划有关吗?
** COBRA：和维纳斯计划无关。光之社区属于新亚特兰计划的一部份。
** 目前外国人要加入这个社区的方法是我们跟这家公司合股，透过公司名义获得土地。
** 我们要兴建的光之社区附近就有森林、蔬菜、水源，所以不会匮乏，也可以用这块森林打造有机农场。
** 这个光之社区盖好之后电力来源会是太阳能和其它替代能源，水源主要是地下水。
** 至于价位和搬迁费用请联络Cobra或找Jedi询问。
** 与会者：请问我搬进去之后就要永远住在光之社区吗?
** COBRA：搬过去只是在那盖房子不用永远住在那边，可以邀请朋友一起去住。
** 交通还算方便，当地会有接驳巴士。距离市中心30分钟，基本设施都有。
** COBRA：这是独立专案，和其他听到团体无关。
** 与会者：房子是一般住家住的房子还是家庭住宅?
** COBRA：这些房子大小可以依照需求而定，看有多少土地再来决定盖多大的房子。
** 与会者：Cobra会参加这项计划吗?
** COBRA：我不会自己亲自跑去当村长，我只是给大家一个机会创造新的世界。
** 光之社区会围绕社区活动中心开始扩建，计划还在发展阶段，可以跟当地建筑师、工程师合作打造光之社区，一起集思构想打造理想的社区型态。光之社区就是事件后的模范社区，让大家知道如何生活，我们现在著手先做才不会都只是空谈。
** 我们会按照这个模范社区当作范本，在各地複製打造各地当地的光之社区，清迈将会有一个光之社区。
** 与会者：这个社区这裡居住的人他的国籍怎麽办，属于哪个国家，出入怎麽办?
** COBRA：所有国籍的人都欢迎加入只要你有心都欢迎加入。并不需要放弃原本的国籍。
** 与会者：要在那边生活是不是得找到工作才能搬到那边，还是当地可以提供工作机会让我们在那能够生活。
** COBRA：初期可能没有工作机会，未来安定后大家可以使用网路创业。我不当老闆的。大家可以做些合法又正当的事情来获得收入。
** 算是种子模范社区，这个社区还有很多我们没看到的愿景，我们走一步看一步，如果有新的想法也可以来做看看。
** 大家要把光之社区当作房地产投资的话也可以，只要在合理的情况下，住两个月另外10个月租给别人。这是不会公开给社会大众知道的社区必须严格审核才能住进来的。
** 虽然光之社区是独立互相合作，这裡没有村长和牧师，没有谁比较高尚也没有种族歧视，这不是Cobra邪教。我自己只是提供这个机会跟资讯而已，这不是要搞Cobra个人崇拜。
** 与会者：你们会跟乌本图合作吗?
** COBRA：如果乌本图愿意配合当然是很好。不管是乌本图或者维纳斯或者新亚特兰提斯计划，只要对人类好的都可以合作。这是我们自己要主动出击的一种创办社区计划，我们要自己走出第一步，我们也欢迎大家互相交流经验。
** 我们继续。现在大家都知道显化法则原理了，大家住在这裡不用担心金钱问题，大家都懂得显化法则金钱就不会是个问题，既然大家都知道显化法则，自然能显化出旅费和适当的生活费来到这个社区。只要第一个社区建好之后，其它社区也会在世界各地以指数性的成长。这并不像是传统的社区裡每个房子长得都一样，我们要打造的社区代表全新的世界，虽然同样叫社区但在本质上是不一样的，在这个光之社区不会推行宗教信仰，大家只要互相共处就行了。
** 将来大家可以显化一个白水晶切出来的浴缸，超光速粒子白水晶切出来的浴缸。只要有愿景愿意做就一定会做到，用这种浴缸洗澡等于每天用超光速粒子水洗澡，当然我们会研发新的科技，将来会在这社区安装超输出装置，将来会普及到全世界。唯一边界就只剩下天空了。
** 我们可以引进一些现有的科技，现在欢迎Alex介绍对人类非常有帮助的雷射科技。
** Alex：我简单介绍这些科技的原理，我们都知道身体有个光体有时候会为气场，在可见光以外的身体，这个光体跟我们身体所有系统细胞相连的。光体连结到情绪和心智，光体也连结到乙太和更高维度的能量身体，我们也知道身体有经络，他也像电缆线一样连结来自内外的能量，穴位经络就是体内的电浆线性通道，气场就是个电浆场。
** 身体也符合碎形原理。 耳朵可以看到身体全部症状，眼睛也是，耳朵就像眼睛的缩影，丹田也是全身的缩影和全身有连结的，手脚穴位都能反应身体的状况。
** 我们也可以用各种方法影响身体周遭的能量场也就是气场，我们也可以用气场照相仪来看气场有没有改善，
** 我们知道植物会有光合作用，吃这些植物时实际上是在吃植物裡面的光，蔬果裡面有彩虹的颜色，当我们吃蔬果时都在吃下不同频率的光。
** 我们的虹膜也跟身体所有细胞有连结，所以看一个人的虹膜就能知道一个人身体器官的状况了。我们用不同颜色的光，再用光所携带的资讯就可以影响那个人身体的系统和器官，已经有科学研究证实光可以修复受损的细胞，这叫做光修复效应。
** 光能医学有各种可能性。今天就不提太多。曼陀罗光能仪使用的是谐振的光波也就是雷射波，是种在量子层面的光。这台机器裡面内建各种谐振频率资料库，一旦使用资料库可以从身体产生身心灵各方面的影响。
** 这台机器裡面有些资料库的频率算是身体的基础频率。这些频率会告诉身体应该用什麽样的频率进行振动，身体细胞有时振动频率太高或太低不在理想的状态，只要我们对身体使用正确频率就能对身体的频率进行校准，现在大家可以看到这台机器。
** 大家已经很熟悉这台机器了，我们也在研发更多的好料，这是第一次展示这项技术，这个穹顶状的装置。
** 这有点像纯量波产生的装置，这个装置除了可以散发光子场。这个可以产生光子场还能产生纯量波场，还能使用导光水晶的用法。
** 也可以把这些资讯输入水裡面，透过喝水吸收正确的频率，有些人知道顺势疗法，可以把那药物打到水裡面进行顺势疗法。基本上有这台光能仪就像在自己家开个药局。也可以用这台仪器设定水晶，我们可以在水晶上设定很会演讲学习语言的程式，或者帮助你放鬆的程式，把他带到身体上面就有相对应的效果。
** 这个是我们正在开发中的雷射坠饰，正式版会漂亮些，会放入已经设定好的水晶，接著雷射会帮忙散发水晶设定好的程式，这个水晶坠饰就像扩大器一样透过雷射放大水晶裡面设定好的效果。
** 这些机器都有搭配一台曼陀罗扫描仪，扫描这个人身体需要哪些程式，也可以用平板选择自己想要的程式。
** 与会者：这台机器可以修复DNA吗?
** Alex：这台机器有特定程式可以清除DNA负面记忆和想法甚至可以修复DNA。
** 科学家其实知道可以用近红外线照射粒线体来修复整个细胞。基本上这有可能恢复人类潜藏的12股DNA?
** 与会者：可以用这台机器治疗癌症吗?
** Alex：这台机器不能宣称有任何疗效，只能说用光线纾压并且调节免疫系统；进而有助于改善癌症患者的生活
** COBRA：待会有兴趣的人可以在后面跟Alex联络。
** 这是我们未来一部份的缩影，我们现在开始显化光之社区，还有新科技和超光速粒子浴缸。
** 
** 扬升光柱
** 
** 现在来说扬升光柱。到底什麽是扬升光柱，昨天有讲到我是临在，现在要做个冥想呼请我是临在，透过扬升光柱进入自己的身体，昨天冥想做的光柱其实就是扬升光柱，扬升光柱其中一个面向是来自我是临在的光柱贯穿三维世界的肉体。
** 扬升光柱另一个面向是银河联盟母船发送光柱到我们肉体，现在银河联盟母船停泊位置是在地球内部屏障内，昨天讲到过去三年银河联盟母船停泊在太阳圈之外，去年文章写到昴宿星人在地球周围搭载超光速粒子内部屏障，12,000公里，内部屏障是距离地球12,000公里高的地方，那算是章鱼的头部顶端。现在银河联盟母船驻扎在这个区域，银河联盟母船就驻扎在章鱼的头外面。
** 大家可以用意识与银河联盟母船连结，大家可以观想这道光柱从银河联盟母船发出，想像银河联盟母船发出巨大的能量光柱到我们身体上面。大家呼请扬升光柱的临在，扬升光柱就会降下来，这个扬升光柱会进入我们肉体，这个扬升光柱有助于你个人的扬升，从现在开始到未来。现在大家知道银河联盟母船的驻扎位置了，我们现在就可以用意识连结银河联盟母船。
** 银河联盟母船从所在位置发射扬升光柱到我们肉体，只要经常连结这些光柱，这些光柱就会越活跃。
** 就会越来越有可能和银河联盟母船有接触和面对面的交流，银河联盟母船上的光之存有们非常想和我们交流接触，这是我们和他们交流的方式。现在我不会在这做大规模的仪式，目前还有点太早。
** 如果未来几年还没发生事件，还有办会议的话我们就会在这进行，现在只是初期而已，扬升光柱是圣光的脉衝粒子，可以调和并保护我们的能量场和肉体。扬升光柱是非常先进的扬升科技，并不是凭空想像的东西，他是直接从银河联盟母船发出的能量波贯穿我们身体。
** 而进阶版的扬升光柱会把人传送到银河联盟母船上面，我们目前处于初期阶段，透过观想扬升光柱可以让我们更容易连结到银河联盟母船，未来阶段扬升光柱甚至可以把你传送到银河联盟母船上。
** 扬升光柱也可以清除生活周遭的主要异常和保护你。我们即将进入银河大团圆的初步阶段，我们很快就要重获自由了，我们总算可以回家了。大家还想待在这裡的话欢迎留下来，想回家的人就请自便。(图)
** 在这之前，大家必须觉醒回想自己的使命并且100%投入。我们在这分享圣光给所有人。(图)
** 我在今天讲显化过程，过去认为不可能的事情都要用显化法则让它实现，现在显化事件，新亚特兰提斯计划透过显化法则显化新的世界和显化事件。当我在部落格上公开一些指示的时候并不是随意贴一篇文章。部落格上的每一个指示都是计划的一个部份，不是随便发一篇文章而已，在我部落格的主人不光是只有我而已，这个部落格代表7,000万名抵抗运动成员。抵抗运动也会从更高的光明势力接受指引。我们并不孤单并不孤独，虽然战役艰难但我们会赢得最后胜利。
** 感谢大家今天的莅临。感谢主办人Jedi。
** 感谢他安排这场会议，谢谢大家也谢谢两位口译-Terry 和 Patrick。感谢所有来自世界各地的准备转变团队和所有的工作人员。感谢展示光能仪，感谢今天支持我们的龙族团体。
** 感谢抵抗运动，也感谢银河联盟，感谢爱希斯老师，她在她的国家帮助我们，感谢大家不辞辛劳参加这次会议。光的胜利。
** 感谢大家度过殊胜的礼拜天，大家在各地散播圣光。
** 
** 
* 2018.5
** 显化过程
** 显化法则
*** 如果精通显化法则跟显化过程，那就可以重新掌握自己的人生，就可以自由的选择人生中想要认识的人事物以及影响到地球的局势。
** 与会者显化法则经历分享:
*** 与会者:
**** 去年我参加会议完想著如何使用显化法则，我和一位有帕金森氏症的人合作，他说他身上有重要的使命，去年九月他下定决心说，他要治疗好他的帕金森综合症。我记得COBRA说显化法则失败原因是因为我们太早放弃了，因为我们看不到未来的结果。就在九月份，他下定决心的那一刻，他的朋友打电话联络到我，他开始讲到地球解放之类的事情。
**** 今年一月我就邀请这位帕金森氏症的朋友，邀到我的地方接受疗癒，他之后就觉得身体好多了。
**** 今年四月在我们装了超光速粒子舱，他发出抉择时当时我们还没订超光速粒子舱，在今年四月他躺完之后身体有很大的改变。我就知道改变是从你下定决心那一刻开始的，虽然看不到未来，但当你下定决心时命运巨轮就开始转动了。
*** 与会者:
**** 对于显化法则我非常有体会了，我显化大大小小无数次了。我的家人，我在2016年觉醒后非常…，我家裡人对我有影响，我担心他们让我有担忧让我没办法很好做我的使命，当时跟光明势力求助，我听冥想时……事情，1..2个月后出现一位我不认识的人，帮我解决我家人问题，我现在对我家人没有后顾之忧了，所以抵抗运动招募我的话我随时都可以走。
**** 第一次听到如意宝珠时，我就非常有感觉，我自己花了些钱买如意宝珠。我的工作在大陆各地出差，我就到处埋宝珠，我的薪水是固定的，不会有额外的收入，但是我花出去的钱很容易就回来了。
**** 最重要的是我用了显化法则才来到这裡，因为扬升会议是5/12~5/13号，我的工作在三月就安排一场工作会议在5/11~5/13号，也因此我就没办法参加会议，但当时我想参加5/16号的聚会，所以我就冥想祈请让我来到台湾，然后在……号我收到通知我的工作取消了，所以我就提前来到了台湾。显化法则非常好，只要专注意念就一定会显化很快。
** 要知道现在这个实体世界实相并不是固定不变的，我们现在实体世界看到的实相不过是能量世界发生的过程总和。地球上看到的每个人事物，都是在过去大家所有抉择的总和。
** 现在会议场地一开始就是处于建筑师裡面的想法，一开始在设计师和建筑师脑袋裡构建出来，接著这个房子的高度跟法规都是所有人共同决定创造出来的。当这群人有最强大的愿景跟显化意念的时候，他就可以显化出他想要的事物。如果你意念比老闆强，原本的工作就可以推掉然后来这场会议。
** 如果你想要做的事情符合圣光也符合光明势力的旨意的话那这种结果会更容易显化。我们每个想法跟意念都会在时空连续体裡产生涟漪，所以是意念塑造实相。
** 现在要讲显化法则。现在市面上写著很多显化法则(吸引力法则)的书，但这些书是不完整的内容，所以很多人会觉得练习显化法则很挫折好像也没什麽用，因为外面坊间教导的并不完整，现在我要跟大家讲述完整的显化法则。
** 
** 显化法则第一个步骤是抉择:
** 
** 抉择是我们意志我是临在的反射缩影，抉择代表我们想要显化还有我们想要创造的东西。
** 抉择是一个基于我们自由意志我是临在的一个行动，当大家很清楚明确自己想要什麽的时候，你的抉择才会明确。一个人有时会心猿意马，决策过程当中，就是要整合不同面向的自我，将所有的面向整合为一。每个人都受到特定的编程，我们都受到编程认为我们需要或者想要什麽东西，但这些编程下的想法不代表是我们真正想要的东西。
** 
** 我们讲些例子:
*** 举例来说有些人本身有艺术方面的才能，觉得我未来应该要去作画。但问题来了，他的家族中祖父都是医生，所以他爸爸希望他儿子去当医生，所以当你住在这个家庭裡面，这个原本可能当艺术家的人最后却当了医生，很多人都希望子承父业，所以艺术家也会被迫去当医生，可是这个人想去当艺术家。
*** 最后你可能会去服从你父亲的建议然后去学医，可能这个人会认为这是他自己的决定，但是他内在有个声音认为这不太对劲。你可能会显化这个抉择然后你决定学医最后你变成了医生，但你不会有快乐的生活，因为这不是基于你自由意志的选择。
*** 所以自由意志的意义在于你知道你真正想要什麽，然后付出行动。你的自由意志有时是和这个社会不一致的，这就看你去如何抉择了。
** 
** 第一阶段攸关我们的抉择，这时可以选择随波逐流跟著控制编程走，或者基于自由意志听从高我的指引抉择，这是每一天我们要做抉择之前先做的选择。
** 基本上这个社会的设置就是要让我们不去听从自由意志，这世界上有很多种规范来限制人类的行为和想法，怎麽穿、怎麽喝、怎麽吃，如果打破这些规则，社会大众就会对你有强烈反应，这是非常巧妙的控制，变成人们会互相控制、互相约束。
** 所以控制矩阵不光是一小搓阴谋控制一大票人，控制矩阵也是人与人之间的互相控制。从某个层面来讲，我们这300多人之间就在互相制约著，是否符合社会的规范。我知道这个控制矩阵的结构，我可以在15秒内说一句话惹毛大家，我知道这个控制编程是如何运作的，但是我不会去这麽做。每个人都在检查身边的人是否符合这些规范，控制矩阵会让大家监视彼此，这是控制矩阵的基本结构。
** 
** 如果想要使用显化法则，我们首先要使用自己的自由意志，好比你一开始想要成为艺术家而不是医生，那就开始学艺术，因为学习艺术是你自由意志的缩影，让你可以过更快乐的人生。
** 这社会其中一个控制编程就是让你认为当艺术家会饿死并且不会成功，但事实上艺术是没有限制的，现在很多艺术家日进斗金赚数十亿，因为这些艺术家他们相信这个世界是无限的，没有限制的。
** 他们知道自由意志会打开一个无限丰盛的门户，不管这个抉择是大是小，这个抉择都是通用的。事实上显化1块钱跟显化10亿美元都是同一个原理，显化事件跟显化一杯咖啡也是同一个原理。差别在于时间，越複杂的计划越需要时间去显化。
** 
** 如果大家想了解自己的自由意志做出选择，一定要先对自己诚实，所以要诚实的问自己我这一生到底要什麽，所以显化法则第一步就是有明确的抉择。当你对自己100%诚实，完全不在意社会对我们的眼光看法，所谓的小我的就会消散，因为小我这东西只不过是让人们服从社会规范的概念而已。
** 当大家对于自己完全真诚，完全了解自己真心想要什麽的时候，你的抉择和行动都会跟你的高我是一致的。执政官有非常强大的控制编程，这些控制编程让人们觉得你的想法和慾望是自私的，这是一个非常强大的控制机制，也是非常强大的控制编程。
** 每个人的愿望跟期望甚至是慾望都是我们人生的指南，这些可以让我们更了解自己，其实我们人生中最梦幻的事情都与我们最崇高的使命是一致的，对于我们的慾望和期望，这些东西可以帮我们引导到最理想的生活。
** 我们的期望和慾望可能跟我们周遭的大环境跟社会不太相符。这些想法和我们的慾望也代表我们有办法在控制矩阵打开一道裂缝，那个时候也代表我们可以实践自己的使命，所以显化法则第一个步骤是要先有明确的抉择。
** 
** 显化法则的第二步骤是祈请:
** 
** 祈请意思就是使用我们情绪的力量，将我们想要的东西下定决心吸引到我们身边。首先要有抉择，我们要用所有热心渴望来吸引我们的抉择、我们想要的东西。我们这股强大的情绪会在身边形成强大的漩涡场，这股漩涡能量场可以把我们下决心想要的东西引到我们身边。
** 祈请也代表可以呼请光明势力帮助我们显化，我们可以用祈请、用祷告、也可以用冥想或者观想，也可以呼请光明势力、呼请天使、呼请扬升大师们来帮助我们的显化。
** 
** 显化法则的第三步骤就是具体的行动:
** 
** 具体行动不代表我们要拚死拚活的努力工作，我说的具体行动是一个投入热情而且按部就班的行动，只要用正确方法来做的话，具体行动上可以非常轻鬆和顺利。
** 如果大家一直重複使用这三个显化法则三步骤，大家把显化法则当电脑程式一样按步就班反覆使用的话，我向大家保证你绝对可以显化你想要的东西。
** 
** 我刚刚说过，显化法则其中的最主要一个问题就是有些人太早就放弃了，实体世界并不是一个能量很流动的世界，算是一个有点僵化的世界，这就是为什麽显化要花一段时间的原因，显化法则不是一瞬间就能发生的事情，需要一些时间来显化。
** 所以我们需要不断的反覆使用显化法则直到我们想要的东西显化的那一天。如果我们现在需要一杯咖啡只需要五分钟，显化一间新房子可能要花五年，显化出事件可能要十年，这些显化都需要花些时间来完成。
** 如果想要显化一间新房子，但在显化过程的第三年就放弃了，那这样就是在浪费时间，如果你的显化坚持了五年，那麽你就可以换到你想要的新房子了。所以关键就是绝对绝对不要放弃，坚持再坚持。
** 当你完全跟你的自由意志以及高我灵魂合一的时候，你等于是在改变地球控制矩阵的结构。我们是被选上的一群人，我们这群人要把新的实相带入这个地表世界，所以我们的显化过程也等于正在改变整个地球社会。
** 
** 我来说一个显化的例子。18世纪时罗斯柴尔德家族决定在地球创建新世界秩序，罗斯柴尔德知道这项计划必须要花200年的时间，罗斯柴尔德知道他们没办法活到计划实现的那一天，可是他们决定要用这一生实现这个计划甚至把这些计划传承给他们的儿子跟孙子。我们现在的金融系统是罗斯柴尔德家族花费250年精心打造的结果，如果我们想要创造新的金融体系就要跟罗斯柴尔德一样的投入和用心。
** 我们不需要花250年，这一次我们可能花比较少时间，大家愿不愿意花5~10年，我们不会花费250年，我们会让它更快显化，我们不需要花费那麽多时间，你准备好用1年、5年或者20年的努力来显化它吗，是还是不是？
** 我们的计划一定会比他们成功，我们的计划是跟神圣计划相关的，我们想要的是全世界所有人的丰盛，而不只是一小群权贵人士的丰盛。有一个非常强大的光明势力在支持我们的计划。
** 在光之工作者的圈子裡面，要实现显化问题是人与人之间的关係。光之工作者之间经常发生衝突，光之工作者之间的衝突阻碍了正面的人际关係显化，这也是我们建立新社会的主要障碍。所以我会在今天下午讲述关于新人际关係的事情。
** 
** 所以显化法则就是一直重複刚刚我所说的三个显化步骤，如果大家重複使用这个显化法则的话一定会显化出来，使用这个显化法则没有限制，大家越是相信，显化成功的可能性就越大。大家不要限制自己能显化的东西，因为任何事情都是只要花时间就一定会显化。
** 
** 问答时间:
*** 与会者:我现在跟一些具有合一意识的伙伴显化一个大团结不再有分裂跟纷争，我们也试著沟通跟努力，最近会做很多动作让我们在华人社区有更多团结，最近燕妮尝试用扭曲扬升会议、扭曲抵抗运动招募内容，遇到一些比较棘手的问题，也跟一些群组不要有衝突，Cobra你是否有解决这个问题的更好的方式？
*** Cobra:我不对她发表任何评论。下午时我会讲更多关于新社区的内容。这应该是这些衝突的解决方法。
*** 与会者:每个人都有自由意志，我想显化的事情跟对方想显化的东西产生衝突该怎麽办?
*** COBRA:如果你的抉择符合你的高我旨意就会显化，其他人的自由意志也不得不跟著最高实相去调整，符合更崇高的实相的抉择会被显化出来，基本上这就是我们的社会演变和进化的过程。
*** 与会者:我们在新时代运动观念裡认为人跟人的互动是基于频率，面对生活中负面的人事物，这些是不是自己内在投射而显化发生的实相?
*** COBRA:基本上我们内在的弱点都是外在干扰对你的攻击点，我们应该要做的就是对这些外在的干扰说「不」，我会在下午实相过滤说明更清楚一些，感谢大家。
** 
** 心想事成/达成丰盛的技术
** 
** 有些很强大的光之存有，他们会支持我们的显化过程，其中一位最重要的光之存有就是圣哲曼，圣哲曼的计划就是教导人们如何使用显化法则，他也希望教导人们可以显化充满丰盛的新时代，如果大家希望自己的显化过程更快更轻鬆的话就可以呼请圣哲曼的临在，他会支持我们的显化。
** 显化法则有一些很高深的技术，我会在这讲几个进阶的显化技术，其中一个技巧叫做实相塑造法，实相塑造法是一个基于我是临在的神圣意志，实相塑造法是塑造我们人生实相的强大工具。
** 
** 这个图表可以解释天地万物的显化过程，这是一个我昨天有讲过的双挠场螺旋结构，这是这个宇宙神圣几何构造。
** 我有讲过所有实体世界显化出来的东西都是源自高维度灵性世界的想法，我们一开始想要显化的东西都是一个想法和抉择，这个抉择会形成一个显化漩涡，然后这个显化漩涡会经过我们的光体门户来到实体世界。
** 如果大家知道这个原理，大家就可以用自己的专注来显化自己想要的事情，大家把注意力放在一个地方就可以打开一个门户进而显化自己想要的人事物。如果我很集中的想一个麦克风，盯著这个麦克风15分钟我就可以在我人生中显化出更多的麦克风。
** 也可以用注意力来显化类似的事物，如果大家想要显化丰盛，大家应该要做什麽呢，就是买一枚金币放在自己口袋裡面每天拿出来看一下，大家每一次专注看著这枚金币就会开启一个门户，这门户就会吸引很多的金币，如果觉得金币太贵的话也可以买银币，买一枚银币一样放进自己的口袋裡。
** 一枚银币价钱差不多跟一个大披萨差不多，大家应该都能有足够的收入购买一枚银币。记得去年有个参与会议的人说他用了一个银币当钱母，结果他之后多赚了两百多枚银币，所以这个方法真的管用。
** 如果想要显化一栋房子，可以买一个小模型屋放在自己的口袋裡面，大家每天就可以从口袋拿出模型屋出来看，每天看，这个专注力就会开启门户让你显化出你自己想要的房子，大家真的不用担心，这是很有效的技巧，这个模型屋的样子就会和你理想中的房子是一样的。
** 如果大家不小心买错房子模型整天看的话，那可能就会显化出不同的房子了，这显化技巧是非常具体精确的。
** 我之前就有买一个模型来显化的经验，我显化出来的东西跟我买的模型是一模一样的，所以买来的模型要尽量具体符合自己想要的。
** 
** 在场有没有人会艺术能够做个压缩突破的模型?我们请他帮我们显化事件。
** 我现在有个任务要交给你，请把压缩突破的模型做成3D列印的样子
** COBRA:你要做的模型大小差不多是….，可以放在每週实体聚会上面，大家聚会时就盯著模型看，大家都盯著模型看5~10分钟。
** 与会者:这样的花费会比较昂贵。
** COBRA:可以找团队，找Jedi解决。
** 如果大家想要显化一个东西，最好的办法就是做一个缩小版的模型。如果大家想要太空旅行的话那麽最好在家裡买一个太空船的模型，这是一个非常具体的显化技巧。
** 我们来讲下一个技巧。我们可以做一个梦想地图，这个地图可以引导我们过著理想的人生。现在请大家拿出一张纸，请大家开始画画，来画你认为的理想人生，用你的想像力画出你想像的人生，完全没有限制，想画什麽就画什麽。
** 
** 大家刚刚画的这张图就是各位的梦想地图，大家的实相就会跟著这张梦想地图跟著改变，这是一个非常强大的显化技巧。不光只是图画而已，我在30年前做了一张人生中第一张梦想地图，10年后我在30年前画的梦想地图有80%都实现了。接著我开始画了第二张梦想地图，我到现在还在使用这张地图显化。现在这张地图我已经进行了很多显化，我在地图上画任何我想要的东西，即使只是小事情，这是非常强大的显化技巧。
** 大家最好回家画一张更精确、更好的地图，大家可以回家拿全开的纸张画一幅更完整的梦想地图，大家可以把自己的梦想地图画在牆壁上，有空时就可以看一下。
** 
** 现在做一个简单的丰盛冥想:
** 将金黄闪耀的光吸进自己的身体
** 将金黄闪耀的光发送到四面八方
** 保持几分钟时间
** 深呼吸将身体充满更多金黄闪耀的光
** 这道金黄闪耀的光渗透到身体裡所有细胞，充满我们能量场
** 观想自己化为一道金黄闪耀的光柱
** 在此呼请圣哲曼大师的临在
** 帮助大家显化个人、亲朋好友、以及好人的丰盛
** 观想心轮发出金黄闪耀的漩涡、漩涡不断扩展
** 观想金黄闪耀的漩涡吸引丰盛、吸引了黄金跟金钱还有房地产还有美好的车子还有最理想的人生
** 观想一切美好的事物来到自己的人生
** 花一段时间观想金黄闪耀的漩涡吸引一切美好的人事物
** 观想圣哲曼大师放了一枚大金币在我们手上
** 感受大金币的重量跟手感，感觉自己手指上的大金币，这是大家的钱母
** 大家感觉一下手上的这一枚钱母
** 从现在起可以把这个钱母放在口袋裡随身携带
** 如果大家还没有钱母，那麽现在下定决心去买一枚金币/银币然后把这枚钱母放在口袋裡，这枚钱母从现在开始会替我们显化丰盛，圣哲曼大师会加持并且祝福你的决定，他会从现在开始帮助你显化丰盛。
** 感觉所有的金光都停留在这个当下，感觉自己已经下定决心要买一枚钱母(金币/银币)。感觉手上的这一枚金币，现在慢慢的开始将意识带回自己身体。
** 
** 显化过滤法
** 
** 关于显化过程我要讲一个重要事情，(图-生命之花)刚刚我跟大家说过要怎麽显化自己想要的重要东西，但人生中也会碰到我们不想要的事情，而你已经把这些不想要的东西作为你决定的一部分去接受了，其实有一个很简单的方法可以帮助我们清除人生中的负面人事物，这种做法叫做显化逆转法，也叫实相过滤法。
** 显化逆转法就是一个抉择，这个抉择就是不论在任何场合，你再也不会接受某一类人事物出现在你的人生当中。如果人生中出现各种霸凌状况，只要下定决心这种霸凌就会停止。如果上班每天被老闆骂，那只要下一个明确的抉择，老闆就不会骂你了。
** 如果你经常遇到某个人的负面行为，你只要下一个明确的抉择，显化逆转法就可以帮助你挡住那个人的负面行为，我们整体来说人类就是在做一个实相逆转，我们正在逆转有阴谋集团存在的实相，我们要移除阴谋集团。
** 如果有144,000(临界质量)的人一起做实相逆转法的话，阴谋集团就会从此消失。
** 可惜现在大约只有3万人下定决心要移除阴谋集团，基于这个原因阴谋集团的移除过程要花比较多时间。
** 大家有没有这方面心得要分享的
** 与会者:我为了要参加会议，同时在2个餐厅做兼职工作，第一个老闆人不错，但是说话很直接，我就用显化法则跟龙族守护冥想，发现他跟我接近时的气场就比较温柔，我也做女神旋涡。另一个老闆娘也是对我很凶，我回家后做龙族守护冥想结果那老闆娘回家就生病了。
** 另一个做晚班的工作，当时有点累就在想可不可以祈请光明势力让餐厅客人早点回家不要太多人，结果8..9点后就没什麽人了，老闆娘就叫我可以提早回家休息了。
** COBRA:所以显化法则是用于人生当中每件大小事，当大家想要对任何事情说「不」的时候都可以用显化逆转法。大家想要说「是」的话使用显化法则，想说「不」的时候使用显化逆转法。这个时候就是自己在运用自由意志的时刻，今天早上会议到此结束告一段落。
** 待会要接受点化的人一点半前来前排集合，其他人三点见。
